PRAGMA foreign_keys=OFF;--> statement-breakpoint
CREATE TABLE `__new_user_settings` (
	`user_id` text PRIMARY KEY NOT NULL,
	`bpm` integer DEFAULT 120 NOT NULL,
	`click_strong` text DEFAULT 'drum-stick',
	`click_strong_2` text DEFAULT 'drum-stick',
	`click_weak` text DEFAULT 'drum-stick',
	`volume` real DEFAULT 0.8 NOT NULL,
	`count_in` integer DEFAULT 1 NOT NULL,
	`metronome_enabled` integer DEFAULT true NOT NULL,
	`metronome_volume` real DEFAULT 0.8 NOT NULL,
	`bass_enabled` integer DEFAULT true NOT NULL,
	`bass_volume` real DEFAULT 0.7 NOT NULL,
	`bass_complexity` integer DEFAULT 1 NOT NULL,
	`bass_octave_up` integer DEFAULT false NOT NULL,
	`rhodes_enabled` integer DEFAULT false NOT NULL,
	`rhodes_volume` real DEFAULT 0.6 NOT NULL,
	`rhodes_mode` text DEFAULT 'halfNotes' NOT NULL,
	`rhodes_voicing_density` text DEFAULT 'rootless3' NOT NULL,
	`rhodes_layer_mode` text DEFAULT 'none' NOT NULL,
	`rhodes_layer_volume` real DEFAULT 0.5 NOT NULL,
	`piano_enabled` integer DEFAULT false NOT NULL,
	`piano_volume` real DEFAULT 0.7 NOT NULL,
	`piano_profile` text DEFAULT 'swing-sparse' NOT NULL,
	`piano_voicing_density` text DEFAULT 'rootless3' NOT NULL,
	`piano_sample_library` text DEFAULT 'salamander' NOT NULL,
	`piano_randomization_level` text DEFAULT 'off' NOT NULL,
	`drums_enabled` integer DEFAULT true NOT NULL,
	`drums_volume` real DEFAULT 0.7 NOT NULL,
	`drums_ride_enabled` integer DEFAULT true NOT NULL,
	`drums_ride_volume` real DEFAULT 0.7 NOT NULL,
	`drums_stir_enabled` integer DEFAULT true NOT NULL,
	`drums_stir_volume` real DEFAULT 0.6 NOT NULL,
	`drums_hihat_enabled` integer DEFAULT true NOT NULL,
	`drums_hihat_volume` real DEFAULT 0.65 NOT NULL,
	`drums_hihat_openness` integer DEFAULT 0 NOT NULL,
	`drums_bass_drum_enabled` integer DEFAULT true NOT NULL,
	`drums_bass_drum_volume` real DEFAULT 0.7 NOT NULL,
	`drums_snare_enabled` integer DEFAULT true NOT NULL,
	`drums_snare_volume` real DEFAULT 0.8 NOT NULL,
	`drums_crash_enabled` integer DEFAULT true NOT NULL,
	`drums_crash_volume` real DEFAULT 0.8 NOT NULL,
	`drums_crash_frequency` integer DEFAULT 4 NOT NULL,
	`drums_rim_enabled` integer DEFAULT false NOT NULL,
	`drums_rim_volume` real DEFAULT 0.6 NOT NULL,
	`drums_pattern` text DEFAULT 'swing' NOT NULL,
	`drums_humanize_intensity` text DEFAULT 'med' NOT NULL,
	`drums_funk_complexity` text DEFAULT 'medium' NOT NULL,
	`drums_fill_frequency` text DEFAULT '8bars' NOT NULL,
	`drums_randomization_level` text DEFAULT 'off' NOT NULL,
	`drums_fill_complexity` text DEFAULT 'medium' NOT NULL,
	`drums_ride_variation` integer DEFAULT true NOT NULL,
	`drums_snare_ghosts` integer DEFAULT true NOT NULL,
	`drums_bass_drum_variation` integer DEFAULT true NOT NULL,
	`drums_ride_pattern` text DEFAULT 'swingRide' NOT NULL,
	`style` text DEFAULT 'swing' NOT NULL,
	`swing_ratio` real DEFAULT 0.5 NOT NULL,
	`audio_format` text DEFAULT 'aac' NOT NULL,
	`practice_cards` text,
	`midi_device_id` text,
	`midi_channel` integer,
	`solo_tone_id` text,
	`solo_volume` real,
	`ducking_enabled` integer,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
INSERT INTO `__new_user_settings`("user_id", "bpm", "click_strong", "click_strong_2", "click_weak", "volume", "count_in", "metronome_enabled", "metronome_volume", "bass_enabled", "bass_volume", "bass_complexity", "bass_octave_up", "rhodes_enabled", "rhodes_volume", "rhodes_mode", "rhodes_voicing_density", "rhodes_layer_mode", "rhodes_layer_volume", "piano_enabled", "piano_volume", "piano_profile", "piano_voicing_density", "piano_sample_library", "piano_randomization_level", "drums_enabled", "drums_volume", "drums_ride_enabled", "drums_ride_volume", "drums_stir_enabled", "drums_stir_volume", "drums_hihat_enabled", "drums_hihat_volume", "drums_hihat_openness", "drums_bass_drum_enabled", "drums_bass_drum_volume", "drums_snare_enabled", "drums_snare_volume", "drums_crash_enabled", "drums_crash_volume", "drums_crash_frequency", "drums_rim_enabled", "drums_rim_volume", "drums_pattern", "drums_humanize_intensity", "drums_funk_complexity", "drums_fill_frequency", "drums_randomization_level", "drums_fill_complexity", "drums_ride_variation", "drums_snare_ghosts", "drums_bass_drum_variation", "drums_ride_pattern", "style", "swing_ratio", "audio_format", "practice_cards", "midi_device_id", "midi_channel", "solo_tone_id", "solo_volume", "ducking_enabled", "created_at", "updated_at") SELECT "user_id", "bpm", "click_strong", "click_strong_2", "click_weak", "volume", "count_in", "metronome_enabled", "metronome_volume", "bass_enabled", "bass_volume", "bass_complexity", "bass_octave_up", "rhodes_enabled", "rhodes_volume", "rhodes_mode", "rhodes_voicing_density", "rhodes_layer_mode", "rhodes_layer_volume", "piano_enabled", "piano_volume", "piano_profile", "piano_voicing_density", "piano_sample_library", "piano_randomization_level", "drums_enabled", "drums_volume", "drums_ride_enabled", "drums_ride_volume", "drums_stir_enabled", "drums_stir_volume", "drums_hihat_enabled", "drums_hihat_volume", "drums_hihat_openness", "drums_bass_drum_enabled", "drums_bass_drum_volume", "drums_snare_enabled", "drums_snare_volume", "drums_crash_enabled", "drums_crash_volume", "drums_crash_frequency", "drums_rim_enabled", "drums_rim_volume", "drums_pattern", "drums_humanize_intensity", "drums_funk_complexity", "drums_fill_frequency", "drums_randomization_level", "drums_fill_complexity", "drums_ride_variation", "drums_snare_ghosts", "drums_bass_drum_variation", "drums_ride_pattern", "style", "swing_ratio", "audio_format", "practice_cards", NULL, NULL, NULL, NULL, NULL, "created_at", "updated_at" FROM `user_settings`;--> statement-breakpoint
DROP TABLE `user_settings`;--> statement-breakpoint
ALTER TABLE `__new_user_settings` RENAME TO `user_settings`;--> statement-breakpoint
PRAGMA foreign_keys=ON;
