-- Default settings singleton (ADMIN-DEFAULT-INSTRUMENT-SETTINGS).
-- Mirror of user_settings minus the personal fields (user_id, practice_cards,
-- midi_device_id, midi_channel). Holds the "factory" starting point inherited
-- by new users (ensureUserSettings) and guests (useEffectiveSettings).
-- Per-style instrument values are NOT stored here — they resolve at runtime via
-- applyStyleDefaults from StyleProfile; admin overrides go into per_style_overrides.
-- IF NOT EXISTS: runtime ensureTables safety net may have pre-created it.
CREATE TABLE IF NOT EXISTS `default_settings` (
  `id` integer PRIMARY KEY NOT NULL,
  `bpm` integer DEFAULT 120 NOT NULL,
  `click_strong` text DEFAULT 'drum-stick',
  `click_strong_2` text DEFAULT 'drum-stick',
  `click_weak` text DEFAULT 'drum-stick',
  `volume` real DEFAULT 0.8 NOT NULL,
  `count_in` integer DEFAULT 1 NOT NULL,
  `metronome_enabled` integer DEFAULT true NOT NULL,
  `metronome_volume` real DEFAULT 0.8 NOT NULL,
  `metronome_mode` text DEFAULT 'both' NOT NULL,
  `metronome_strong_enabled` integer DEFAULT true NOT NULL,
  `metronome_strong_volume` real DEFAULT 0.8 NOT NULL,
  `metronome_strong2_enabled` integer DEFAULT true NOT NULL,
  `metronome_strong2_volume` real DEFAULT 0.8 NOT NULL,
  `metronome_weak_enabled` integer DEFAULT true NOT NULL,
  `metronome_weak_volume` real DEFAULT 0.8 NOT NULL,
  `bass_enabled` integer DEFAULT true NOT NULL,
  `bass_volume` real DEFAULT 0.7 NOT NULL,
  `bass_complexity` integer DEFAULT 1 NOT NULL,
  `bass_variant` text,
  `bass_tension` text DEFAULT 'clean',
  `bass_humanize` text,
  `bass_use_muted_notes` integer DEFAULT true NOT NULL,
  `rhodes_enabled` integer DEFAULT false NOT NULL,
  `rhodes_volume` real DEFAULT 0.6 NOT NULL,
  `rhodes_mode` text DEFAULT 'halfNotes' NOT NULL,
  `rhodes_voicing_density` text DEFAULT 'rootless3' NOT NULL,
  `rhodes_layer_mode` text DEFAULT 'none' NOT NULL,
  `rhodes_layer_volume` real DEFAULT 0.5 NOT NULL,
  `piano_enabled` integer DEFAULT false NOT NULL,
  `piano_volume` real DEFAULT 0.7 NOT NULL,
  `piano_profile` text DEFAULT 'swing-sparse' NOT NULL,
  `piano_voicing_density` text DEFAULT 'rootless3' NOT NULL,
  `piano_sample_library` text DEFAULT 'salamander' NOT NULL,
  `piano_tension` text DEFAULT 'clean',
  `piano_humanize` text,
  `drums_enabled` integer DEFAULT true NOT NULL,
  `drums_volume` real DEFAULT 0.7 NOT NULL,
  `drum_kit` text DEFAULT 'jazz-drum-kit' NOT NULL,
  `style` text DEFAULT 'swing' NOT NULL,
  `per_style_overrides` text,
  `swing_ratio` real DEFAULT 0.5 NOT NULL,
  `audio_format` text DEFAULT 'aac' NOT NULL,
  `solo_tone_id` text DEFAULT 'rhodes-jrhodes3c',
  `solo_volume` real,
  `ducking_enabled` integer,
  `created_at` integer NOT NULL,
  `updated_at` integer NOT NULL
);
