/* AUTO-GENERATED by the Constructor "Опубликовать в код" action. Do not edit by hand.
 * When non-empty, this map fully replaces the base definitions. */
export const GENERATED_BASS_MOLECULES: Record<string, unknown> = {
  "bass-up-swing-walk-basic__swing": {
    "id": "bass-up-swing-walk-basic__swing",
    "style": "swing",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.82,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 480,
        "velocity": 0.68,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.76,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 1440,
        "velocity": 0.7,
        "durationTicks": 480
      }
    ]
  },
  "bass-up-swing-walk-basic__bossa": {
    "id": "bass-up-swing-walk-basic__bossa",
    "style": "bossa",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.82,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 480,
        "velocity": 0.68,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.76,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 1440,
        "velocity": 0.7,
        "durationTicks": 480
      }
    ]
  },
  "bass-up-swing-walk-basic__ballad": {
    "id": "bass-up-swing-walk-basic__ballad",
    "style": "ballad",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.82,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 480,
        "velocity": 0.68,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.76,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 1440,
        "velocity": 0.7,
        "durationTicks": 480
      }
    ]
  },
  "bass-up-swing-walk-135__swing": {
    "id": "bass-up-swing-walk-135__swing",
    "style": "swing",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.82,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 480,
        "velocity": 0.68,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.76,
        "durationTicks": 480
      },
      {
        "sound": "muted",
        "atTick": 1440,
        "velocity": 0.7,
        "durationTicks": 480
      }
    ]
  },
  "bass-up-swing-walk-135__bossa": {
    "id": "bass-up-swing-walk-135__bossa",
    "style": "bossa",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.82,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 480,
        "velocity": 0.68,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.76,
        "durationTicks": 480
      },
      {
        "sound": "muted",
        "atTick": 1440,
        "velocity": 0.7,
        "durationTicks": 480
      }
    ]
  },
  "bass-up-swing-walk-135__ballad": {
    "id": "bass-up-swing-walk-135__ballad",
    "style": "ballad",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.82,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 480,
        "velocity": 0.68,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.76,
        "durationTicks": 480
      },
      {
        "sound": "muted",
        "atTick": 1440,
        "velocity": 0.7,
        "durationTicks": 480
      }
    ]
  },
  "bass-up-swing-walk-5173__swing": {
    "id": "bass-up-swing-walk-5173__swing",
    "style": "swing",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.82,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 480,
        "velocity": 0.68,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.76,
        "durationTicks": 480
      },
      {
        "sound": "muted",
        "atTick": 1440,
        "velocity": 0.66,
        "durationTicks": 480
      }
    ]
  },
  "bass-up-swing-walk-5173__bossa": {
    "id": "bass-up-swing-walk-5173__bossa",
    "style": "bossa",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.82,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 480,
        "velocity": 0.68,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.76,
        "durationTicks": 480
      },
      {
        "sound": "muted",
        "atTick": 1440,
        "velocity": 0.66,
        "durationTicks": 480
      }
    ]
  },
  "bass-up-swing-walk-5173__ballad": {
    "id": "bass-up-swing-walk-5173__ballad",
    "style": "ballad",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.82,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 480,
        "velocity": 0.68,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.76,
        "durationTicks": 480
      },
      {
        "sound": "muted",
        "atTick": 1440,
        "velocity": 0.66,
        "durationTicks": 480
      }
    ]
  },
  "bass-up-swing-walk-approach__swing": {
    "id": "bass-up-swing-walk-approach__swing",
    "style": "swing",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.82,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 480,
        "velocity": 0.68,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.76,
        "durationTicks": 480
      },
      {
        "sound": "muted",
        "atTick": 1440,
        "velocity": 0.66,
        "durationTicks": 480
      }
    ]
  },
  "bass-up-swing-walk-approach__bossa": {
    "id": "bass-up-swing-walk-approach__bossa",
    "style": "bossa",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.82,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 480,
        "velocity": 0.68,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.76,
        "durationTicks": 480
      },
      {
        "sound": "muted",
        "atTick": 1440,
        "velocity": 0.66,
        "durationTicks": 480
      }
    ]
  },
  "bass-up-swing-walk-approach__ballad": {
    "id": "bass-up-swing-walk-approach__ballad",
    "style": "ballad",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.82,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 480,
        "velocity": 0.68,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.76,
        "durationTicks": 480
      },
      {
        "sound": "muted",
        "atTick": 1440,
        "velocity": 0.66,
        "durationTicks": 480
      }
    ]
  },
  "bass-up-swing-walk-half-note__swing": {
    "id": "bass-up-swing-walk-half-note__swing",
    "style": "swing",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.8,
        "durationTicks": 960
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.72,
        "durationTicks": 960
      }
    ]
  },
  "bass-up-swing-walk-half-note__bossa": {
    "id": "bass-up-swing-walk-half-note__bossa",
    "style": "bossa",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.8,
        "durationTicks": 960
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.72,
        "durationTicks": 960
      }
    ]
  },
  "bass-up-swing-walk-half-note__ballad": {
    "id": "bass-up-swing-walk-half-note__ballad",
    "style": "ballad",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.8,
        "durationTicks": 960
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.72,
        "durationTicks": 960
      }
    ]
  },
  "bass-up-swing-turnaround__swing": {
    "id": "bass-up-swing-turnaround__swing",
    "style": "swing",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.84,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 480,
        "velocity": 0.7,
        "durationTicks": 480
      },
      {
        "sound": "muted",
        "atTick": 960,
        "velocity": 0.72,
        "durationTicks": 480
      },
      {
        "sound": "muted",
        "atTick": 1440,
        "velocity": 0.74,
        "durationTicks": 480
      }
    ]
  },
  "bass-up-swing-turnaround__bossa": {
    "id": "bass-up-swing-turnaround__bossa",
    "style": "bossa",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.84,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 480,
        "velocity": 0.7,
        "durationTicks": 480
      },
      {
        "sound": "muted",
        "atTick": 960,
        "velocity": 0.72,
        "durationTicks": 480
      },
      {
        "sound": "muted",
        "atTick": 1440,
        "velocity": 0.74,
        "durationTicks": 480
      }
    ]
  },
  "bass-up-swing-turnaround__ballad": {
    "id": "bass-up-swing-turnaround__ballad",
    "style": "ballad",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.84,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 480,
        "velocity": 0.7,
        "durationTicks": 480
      },
      {
        "sound": "muted",
        "atTick": 960,
        "velocity": 0.72,
        "durationTicks": 480
      },
      {
        "sound": "muted",
        "atTick": 1440,
        "velocity": 0.74,
        "durationTicks": 480
      }
    ]
  },
  "bass-up-swing-walk-chromatic__swing": {
    "id": "bass-up-swing-walk-chromatic__swing",
    "style": "swing",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.84,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 480,
        "velocity": 0.7,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.78,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 1440,
        "velocity": 0.72,
        "durationTicks": 480
      }
    ]
  },
  "bass-up-swing-walk-chromatic__bossa": {
    "id": "bass-up-swing-walk-chromatic__bossa",
    "style": "bossa",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.84,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 480,
        "velocity": 0.7,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.78,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 1440,
        "velocity": 0.72,
        "durationTicks": 480
      }
    ]
  },
  "bass-up-swing-walk-chromatic__ballad": {
    "id": "bass-up-swing-walk-chromatic__ballad",
    "style": "ballad",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.84,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 480,
        "velocity": 0.7,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.78,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 1440,
        "velocity": 0.72,
        "durationTicks": 480
      }
    ]
  },
  "bass-up-swing-walk-triplet__swing": {
    "id": "bass-up-swing-walk-triplet__swing",
    "style": "swing",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.84,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 480,
        "velocity": 0.7,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.76,
        "durationTicks": 160
      },
      {
        "sound": "regular",
        "atTick": 1120,
        "velocity": 0.64,
        "durationTicks": 160
      },
      {
        "sound": "regular",
        "atTick": 1280,
        "velocity": 0.62,
        "durationTicks": 160
      },
      {
        "sound": "regular",
        "atTick": 1440,
        "velocity": 0.7,
        "durationTicks": 480
      }
    ]
  },
  "bass-up-swing-walk-triplet__bossa": {
    "id": "bass-up-swing-walk-triplet__bossa",
    "style": "bossa",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.84,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 480,
        "velocity": 0.7,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.76,
        "durationTicks": 160
      },
      {
        "sound": "regular",
        "atTick": 1120,
        "velocity": 0.64,
        "durationTicks": 160
      },
      {
        "sound": "regular",
        "atTick": 1280,
        "velocity": 0.62,
        "durationTicks": 160
      },
      {
        "sound": "regular",
        "atTick": 1440,
        "velocity": 0.7,
        "durationTicks": 480
      }
    ]
  },
  "bass-up-swing-walk-triplet__ballad": {
    "id": "bass-up-swing-walk-triplet__ballad",
    "style": "ballad",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.84,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 480,
        "velocity": 0.7,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.76,
        "durationTicks": 160
      },
      {
        "sound": "regular",
        "atTick": 1120,
        "velocity": 0.64,
        "durationTicks": 160
      },
      {
        "sound": "regular",
        "atTick": 1280,
        "velocity": 0.62,
        "durationTicks": 160
      },
      {
        "sound": "regular",
        "atTick": 1440,
        "velocity": 0.7,
        "durationTicks": 480
      }
    ]
  },
  "bass-up-swing-walk-octave-leap__swing": {
    "id": "bass-up-swing-walk-octave-leap__swing",
    "style": "swing",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.86,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 480,
        "velocity": 0.66,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.8,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 1440,
        "velocity": 0.72,
        "durationTicks": 480
      }
    ]
  },
  "bass-up-swing-walk-octave-leap__bossa": {
    "id": "bass-up-swing-walk-octave-leap__bossa",
    "style": "bossa",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.86,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 480,
        "velocity": 0.66,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.8,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 1440,
        "velocity": 0.72,
        "durationTicks": 480
      }
    ]
  },
  "bass-up-swing-walk-octave-leap__ballad": {
    "id": "bass-up-swing-walk-octave-leap__ballad",
    "style": "ballad",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.86,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 480,
        "velocity": 0.66,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.8,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 1440,
        "velocity": 0.72,
        "durationTicks": 480
      }
    ]
  },
  "bass-up-swing-walk-8th__swing": {
    "id": "bass-up-swing-walk-8th__swing",
    "style": "swing",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.82,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 240,
        "velocity": 0.6,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 480,
        "velocity": 0.66,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 720,
        "velocity": 0.58,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.74,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 1200,
        "velocity": 0.62,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 1440,
        "velocity": 0.68,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 1680,
        "velocity": 0.56,
        "durationTicks": 240
      }
    ]
  },
  "bass-up-swing-walk-8th__bossa": {
    "id": "bass-up-swing-walk-8th__bossa",
    "style": "bossa",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.82,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 240,
        "velocity": 0.6,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 480,
        "velocity": 0.66,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 720,
        "velocity": 0.58,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.74,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 1200,
        "velocity": 0.62,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 1440,
        "velocity": 0.68,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 1680,
        "velocity": 0.56,
        "durationTicks": 240
      }
    ]
  },
  "bass-up-swing-walk-8th__ballad": {
    "id": "bass-up-swing-walk-8th__ballad",
    "style": "ballad",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.82,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 240,
        "velocity": 0.6,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 480,
        "velocity": 0.66,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 720,
        "velocity": 0.58,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.74,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 1200,
        "velocity": 0.62,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 1440,
        "velocity": 0.68,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 1680,
        "velocity": 0.56,
        "durationTicks": 240
      }
    ]
  },
  "bass-up-swing-walk-8th-ghost__swing": {
    "id": "bass-up-swing-walk-8th-ghost__swing",
    "style": "swing",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.82,
        "durationTicks": 240
      },
      {
        "sound": "muted",
        "atTick": 240,
        "velocity": 0.34,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 480,
        "velocity": 0.66,
        "durationTicks": 240
      },
      {
        "sound": "muted",
        "atTick": 720,
        "velocity": 0.32,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.74,
        "durationTicks": 240
      },
      {
        "sound": "muted",
        "atTick": 1200,
        "velocity": 0.34,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 1440,
        "velocity": 0.68,
        "durationTicks": 240
      },
      {
        "sound": "muted",
        "atTick": 1680,
        "velocity": 0.44,
        "durationTicks": 240
      }
    ]
  },
  "bass-up-swing-walk-8th-ghost__bossa": {
    "id": "bass-up-swing-walk-8th-ghost__bossa",
    "style": "bossa",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.82,
        "durationTicks": 240
      },
      {
        "sound": "muted",
        "atTick": 240,
        "velocity": 0.34,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 480,
        "velocity": 0.66,
        "durationTicks": 240
      },
      {
        "sound": "muted",
        "atTick": 720,
        "velocity": 0.32,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.74,
        "durationTicks": 240
      },
      {
        "sound": "muted",
        "atTick": 1200,
        "velocity": 0.34,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 1440,
        "velocity": 0.68,
        "durationTicks": 240
      },
      {
        "sound": "muted",
        "atTick": 1680,
        "velocity": 0.44,
        "durationTicks": 240
      }
    ]
  },
  "bass-up-swing-walk-8th-ghost__ballad": {
    "id": "bass-up-swing-walk-8th-ghost__ballad",
    "style": "ballad",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.82,
        "durationTicks": 240
      },
      {
        "sound": "muted",
        "atTick": 240,
        "velocity": 0.34,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 480,
        "velocity": 0.66,
        "durationTicks": 240
      },
      {
        "sound": "muted",
        "atTick": 720,
        "velocity": 0.32,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.74,
        "durationTicks": 240
      },
      {
        "sound": "muted",
        "atTick": 1200,
        "velocity": 0.34,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 1440,
        "velocity": 0.68,
        "durationTicks": 240
      },
      {
        "sound": "muted",
        "atTick": 1680,
        "velocity": 0.44,
        "durationTicks": 240
      }
    ]
  },
  "bass-up-swing-walk-bebop__swing": {
    "id": "bass-up-swing-walk-bebop__swing",
    "style": "swing",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.82,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 480,
        "velocity": 0.68,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.74,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 1200,
        "velocity": 0.62,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 1440,
        "velocity": 0.68,
        "durationTicks": 480
      }
    ]
  },
  "bass-up-swing-walk-bebop__bossa": {
    "id": "bass-up-swing-walk-bebop__bossa",
    "style": "bossa",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.82,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 480,
        "velocity": 0.68,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.74,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 1200,
        "velocity": 0.62,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 1440,
        "velocity": 0.68,
        "durationTicks": 480
      }
    ]
  },
  "bass-up-swing-walk-bebop__ballad": {
    "id": "bass-up-swing-walk-bebop__ballad",
    "style": "ballad",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.82,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 480,
        "velocity": 0.68,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.74,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 1200,
        "velocity": 0.62,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 1440,
        "velocity": 0.68,
        "durationTicks": 480
      }
    ]
  },
  "bass-up-swing-walk-pickup__swing": {
    "id": "bass-up-swing-walk-pickup__swing",
    "style": "swing",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.82,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 480,
        "velocity": 0.66,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.74,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 1440,
        "velocity": 0.68,
        "durationTicks": 240
      },
      {
        "sound": "muted",
        "atTick": 1680,
        "velocity": 0.4,
        "durationTicks": 240
      }
    ]
  },
  "bass-up-swing-walk-pickup__bossa": {
    "id": "bass-up-swing-walk-pickup__bossa",
    "style": "bossa",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.82,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 480,
        "velocity": 0.66,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.74,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 1440,
        "velocity": 0.68,
        "durationTicks": 240
      },
      {
        "sound": "muted",
        "atTick": 1680,
        "velocity": 0.4,
        "durationTicks": 240
      }
    ]
  },
  "bass-up-swing-walk-pickup__ballad": {
    "id": "bass-up-swing-walk-pickup__ballad",
    "style": "ballad",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.82,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 480,
        "velocity": 0.66,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.74,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 1440,
        "velocity": 0.68,
        "durationTicks": 240
      },
      {
        "sound": "muted",
        "atTick": 1680,
        "velocity": 0.4,
        "durationTicks": 240
      }
    ]
  },
  "bass-up-swing-walk-passing__swing": {
    "id": "bass-up-swing-walk-passing__swing",
    "style": "swing",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.82,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 480,
        "velocity": 0.66,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 720,
        "velocity": 0.58,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.74,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 1440,
        "velocity": 0.68,
        "durationTicks": 480
      }
    ]
  },
  "bass-up-swing-walk-passing__bossa": {
    "id": "bass-up-swing-walk-passing__bossa",
    "style": "bossa",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.82,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 480,
        "velocity": 0.66,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 720,
        "velocity": 0.58,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.74,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 1440,
        "velocity": 0.68,
        "durationTicks": 480
      }
    ]
  },
  "bass-up-swing-walk-passing__ballad": {
    "id": "bass-up-swing-walk-passing__ballad",
    "style": "ballad",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.82,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 480,
        "velocity": 0.66,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 720,
        "velocity": 0.58,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.74,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 1440,
        "velocity": 0.68,
        "durationTicks": 480
      }
    ]
  },
  "bass-up-swing-walk-2bar__swing": {
    "id": "bass-up-swing-walk-2bar__swing",
    "style": "swing",
    "bars": 2,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.82,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 480,
        "velocity": 0.66,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.74,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 1440,
        "velocity": 0.68,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 1920,
        "velocity": 0.82,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 2160,
        "velocity": 0.6,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 2400,
        "velocity": 0.66,
        "durationTicks": 240
      },
      {
        "sound": "muted",
        "atTick": 2640,
        "velocity": 0.32,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 2880,
        "velocity": 0.74,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 3120,
        "velocity": 0.62,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 3360,
        "velocity": 0.68,
        "durationTicks": 240
      },
      {
        "sound": "muted",
        "atTick": 3600,
        "velocity": 0.44,
        "durationTicks": 240
      }
    ]
  },
  "bass-up-swing-walk-2bar__bossa": {
    "id": "bass-up-swing-walk-2bar__bossa",
    "style": "bossa",
    "bars": 2,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.82,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 480,
        "velocity": 0.66,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.74,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 1440,
        "velocity": 0.68,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 1920,
        "velocity": 0.82,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 2160,
        "velocity": 0.6,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 2400,
        "velocity": 0.66,
        "durationTicks": 240
      },
      {
        "sound": "muted",
        "atTick": 2640,
        "velocity": 0.32,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 2880,
        "velocity": 0.74,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 3120,
        "velocity": 0.62,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 3360,
        "velocity": 0.68,
        "durationTicks": 240
      },
      {
        "sound": "muted",
        "atTick": 3600,
        "velocity": 0.44,
        "durationTicks": 240
      }
    ]
  },
  "bass-up-swing-walk-2bar__ballad": {
    "id": "bass-up-swing-walk-2bar__ballad",
    "style": "ballad",
    "bars": 2,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.82,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 480,
        "velocity": 0.66,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.74,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 1440,
        "velocity": 0.68,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 1920,
        "velocity": 0.82,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 2160,
        "velocity": 0.6,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 2400,
        "velocity": 0.66,
        "durationTicks": 240
      },
      {
        "sound": "muted",
        "atTick": 2640,
        "velocity": 0.32,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 2880,
        "velocity": 0.74,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 3120,
        "velocity": 0.62,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 3360,
        "velocity": 0.68,
        "durationTicks": 240
      },
      {
        "sound": "muted",
        "atTick": 3600,
        "velocity": 0.44,
        "durationTicks": 240
      }
    ]
  },
  "bass-up-swing-walk-2bar-chromatic__swing": {
    "id": "bass-up-swing-walk-2bar-chromatic__swing",
    "style": "swing",
    "bars": 2,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.86,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 480,
        "velocity": 0.68,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.78,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 1440,
        "velocity": 0.72,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 1920,
        "velocity": 0.84,
        "durationTicks": 240
      },
      {
        "sound": "muted",
        "atTick": 2160,
        "velocity": 0.38,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 2400,
        "velocity": 0.68,
        "durationTicks": 240
      },
      {
        "sound": "muted",
        "atTick": 2640,
        "velocity": 0.34,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 2880,
        "velocity": 0.76,
        "durationTicks": 240
      },
      {
        "sound": "muted",
        "atTick": 3120,
        "velocity": 0.36,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 3360,
        "velocity": 0.7,
        "durationTicks": 240
      },
      {
        "sound": "muted",
        "atTick": 3600,
        "velocity": 0.48,
        "durationTicks": 240
      }
    ]
  },
  "bass-up-swing-walk-2bar-chromatic__bossa": {
    "id": "bass-up-swing-walk-2bar-chromatic__bossa",
    "style": "bossa",
    "bars": 2,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.86,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 480,
        "velocity": 0.68,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.78,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 1440,
        "velocity": 0.72,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 1920,
        "velocity": 0.84,
        "durationTicks": 240
      },
      {
        "sound": "muted",
        "atTick": 2160,
        "velocity": 0.38,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 2400,
        "velocity": 0.68,
        "durationTicks": 240
      },
      {
        "sound": "muted",
        "atTick": 2640,
        "velocity": 0.34,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 2880,
        "velocity": 0.76,
        "durationTicks": 240
      },
      {
        "sound": "muted",
        "atTick": 3120,
        "velocity": 0.36,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 3360,
        "velocity": 0.7,
        "durationTicks": 240
      },
      {
        "sound": "muted",
        "atTick": 3600,
        "velocity": 0.48,
        "durationTicks": 240
      }
    ]
  },
  "bass-up-swing-walk-2bar-chromatic__ballad": {
    "id": "bass-up-swing-walk-2bar-chromatic__ballad",
    "style": "ballad",
    "bars": 2,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.86,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 480,
        "velocity": 0.68,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.78,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 1440,
        "velocity": 0.72,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 1920,
        "velocity": 0.84,
        "durationTicks": 240
      },
      {
        "sound": "muted",
        "atTick": 2160,
        "velocity": 0.38,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 2400,
        "velocity": 0.68,
        "durationTicks": 240
      },
      {
        "sound": "muted",
        "atTick": 2640,
        "velocity": 0.34,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 2880,
        "velocity": 0.76,
        "durationTicks": 240
      },
      {
        "sound": "muted",
        "atTick": 3120,
        "velocity": 0.36,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 3360,
        "velocity": 0.7,
        "durationTicks": 240
      },
      {
        "sound": "muted",
        "atTick": 3600,
        "velocity": 0.48,
        "durationTicks": 240
      }
    ]
  },
  "bass-up-swing-bebop-turnaround__swing": {
    "id": "bass-up-swing-bebop-turnaround__swing",
    "style": "swing",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.84,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 480,
        "velocity": 0.7,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.74,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 1200,
        "velocity": 0.62,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 1440,
        "velocity": 0.68,
        "durationTicks": 240
      },
      {
        "sound": "muted",
        "atTick": 1680,
        "velocity": 0.54,
        "durationTicks": 240
      }
    ]
  },
  "bass-up-swing-bebop-turnaround__bossa": {
    "id": "bass-up-swing-bebop-turnaround__bossa",
    "style": "bossa",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.84,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 480,
        "velocity": 0.7,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.74,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 1200,
        "velocity": 0.62,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 1440,
        "velocity": 0.68,
        "durationTicks": 240
      },
      {
        "sound": "muted",
        "atTick": 1680,
        "velocity": 0.54,
        "durationTicks": 240
      }
    ]
  },
  "bass-up-swing-bebop-turnaround__ballad": {
    "id": "bass-up-swing-bebop-turnaround__ballad",
    "style": "ballad",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.84,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 480,
        "velocity": 0.7,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.74,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 1200,
        "velocity": 0.62,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 1440,
        "velocity": 0.68,
        "durationTicks": 240
      },
      {
        "sound": "muted",
        "atTick": 1680,
        "velocity": 0.54,
        "durationTicks": 240
      }
    ]
  },
  "bass-up-bossa-1-5__swing": {
    "id": "bass-up-bossa-1-5__swing",
    "style": "swing",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.78,
        "durationTicks": 960
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.7,
        "durationTicks": 960
      }
    ]
  },
  "bass-up-bossa-1-5__bossa": {
    "id": "bass-up-bossa-1-5__bossa",
    "style": "bossa",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.78,
        "durationTicks": 960
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.7,
        "durationTicks": 960
      }
    ]
  },
  "bass-up-bossa-1-5__ballad": {
    "id": "bass-up-bossa-1-5__ballad",
    "style": "ballad",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.78,
        "durationTicks": 960
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.7,
        "durationTicks": 960
      }
    ]
  },
  "bass-up-bossa-1-5-octave__swing": {
    "id": "bass-up-bossa-1-5-octave__swing",
    "style": "swing",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.78,
        "durationTicks": 960
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.66,
        "durationTicks": 960
      }
    ]
  },
  "bass-up-bossa-1-5-octave__bossa": {
    "id": "bass-up-bossa-1-5-octave__bossa",
    "style": "bossa",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.78,
        "durationTicks": 960
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.66,
        "durationTicks": 960
      }
    ]
  },
  "bass-up-bossa-1-5-octave__ballad": {
    "id": "bass-up-bossa-1-5-octave__ballad",
    "style": "ballad",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.78,
        "durationTicks": 960
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.66,
        "durationTicks": 960
      }
    ]
  },
  "bass-up-bossa-approach__swing": {
    "id": "bass-up-bossa-approach__swing",
    "style": "swing",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.78,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 480,
        "velocity": 0.66,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.72,
        "durationTicks": 480
      },
      {
        "sound": "muted",
        "atTick": 1680,
        "velocity": 0.62,
        "durationTicks": 240
      }
    ]
  },
  "bass-up-bossa-approach__bossa": {
    "id": "bass-up-bossa-approach__bossa",
    "style": "bossa",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.78,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 480,
        "velocity": 0.66,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.72,
        "durationTicks": 480
      },
      {
        "sound": "muted",
        "atTick": 1680,
        "velocity": 0.62,
        "durationTicks": 240
      }
    ]
  },
  "bass-up-bossa-approach__ballad": {
    "id": "bass-up-bossa-approach__ballad",
    "style": "ballad",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.78,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 480,
        "velocity": 0.66,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.72,
        "durationTicks": 480
      },
      {
        "sound": "muted",
        "atTick": 1680,
        "velocity": 0.62,
        "durationTicks": 240
      }
    ]
  },
  "bass-up-ballad-two-feel__swing": {
    "id": "bass-up-ballad-two-feel__swing",
    "style": "swing",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.74,
        "durationTicks": 960
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.68,
        "durationTicks": 960
      }
    ]
  },
  "bass-up-ballad-two-feel__bossa": {
    "id": "bass-up-ballad-two-feel__bossa",
    "style": "bossa",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.74,
        "durationTicks": 960
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.68,
        "durationTicks": 960
      }
    ]
  },
  "bass-up-ballad-two-feel__ballad": {
    "id": "bass-up-ballad-two-feel__ballad",
    "style": "ballad",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.74,
        "durationTicks": 960
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.68,
        "durationTicks": 960
      }
    ]
  },
  "bass-up-ballad-two-feel-5__swing": {
    "id": "bass-up-ballad-two-feel-5__swing",
    "style": "swing",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.74,
        "durationTicks": 960
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.7,
        "durationTicks": 960
      }
    ]
  },
  "bass-up-ballad-two-feel-5__bossa": {
    "id": "bass-up-ballad-two-feel-5__bossa",
    "style": "bossa",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.74,
        "durationTicks": 960
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.7,
        "durationTicks": 960
      }
    ]
  },
  "bass-up-ballad-two-feel-5__ballad": {
    "id": "bass-up-ballad-two-feel-5__ballad",
    "style": "ballad",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.74,
        "durationTicks": 960
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.7,
        "durationTicks": 960
      }
    ]
  },
  "bass-up-ballad-approach__swing": {
    "id": "bass-up-ballad-approach__swing",
    "style": "swing",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.74,
        "durationTicks": 960
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.7,
        "durationTicks": 480
      },
      {
        "sound": "muted",
        "atTick": 1440,
        "velocity": 0.6,
        "durationTicks": 480
      }
    ]
  },
  "bass-up-ballad-approach__bossa": {
    "id": "bass-up-ballad-approach__bossa",
    "style": "bossa",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.74,
        "durationTicks": 960
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.7,
        "durationTicks": 480
      },
      {
        "sound": "muted",
        "atTick": 1440,
        "velocity": 0.6,
        "durationTicks": 480
      }
    ]
  },
  "bass-up-ballad-approach__ballad": {
    "id": "bass-up-ballad-approach__ballad",
    "style": "ballad",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.74,
        "durationTicks": 960
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.7,
        "durationTicks": 480
      },
      {
        "sound": "muted",
        "atTick": 1440,
        "velocity": 0.6,
        "durationTicks": 480
      }
    ]
  },
  "bass-up-ballad-half-note-walk__swing": {
    "id": "bass-up-ballad-half-note-walk__swing",
    "style": "swing",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.74,
        "durationTicks": 960
      },
      {
        "sound": "regular",
        "atTick": 720,
        "velocity": 0.66,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.68,
        "durationTicks": 480
      },
      {
        "sound": "muted",
        "atTick": 1440,
        "velocity": 0.6,
        "durationTicks": 480
      }
    ]
  },
  "bass-up-ballad-half-note-walk__bossa": {
    "id": "bass-up-ballad-half-note-walk__bossa",
    "style": "bossa",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.74,
        "durationTicks": 960
      },
      {
        "sound": "regular",
        "atTick": 720,
        "velocity": 0.66,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.68,
        "durationTicks": 480
      },
      {
        "sound": "muted",
        "atTick": 1440,
        "velocity": 0.6,
        "durationTicks": 480
      }
    ]
  },
  "bass-up-ballad-half-note-walk__ballad": {
    "id": "bass-up-ballad-half-note-walk__ballad",
    "style": "ballad",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.74,
        "durationTicks": 960
      },
      {
        "sound": "regular",
        "atTick": 720,
        "velocity": 0.66,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.68,
        "durationTicks": 480
      },
      {
        "sound": "muted",
        "atTick": 1440,
        "velocity": 0.6,
        "durationTicks": 480
      }
    ]
  },
  "bass-el-funk-pocket__funk": {
    "id": "bass-el-funk-pocket__funk",
    "style": "funk",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.82,
        "durationTicks": 480
      },
      {
        "sound": "muted",
        "atTick": 240,
        "velocity": 0.4,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.74,
        "durationTicks": 480
      },
      {
        "sound": "muted",
        "atTick": 1680,
        "velocity": 0.42,
        "durationTicks": 240
      }
    ]
  },
  "bass-el-funk-pocket__latin": {
    "id": "bass-el-funk-pocket__latin",
    "style": "latin",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.82,
        "durationTicks": 480
      },
      {
        "sound": "muted",
        "atTick": 240,
        "velocity": 0.4,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.74,
        "durationTicks": 480
      },
      {
        "sound": "muted",
        "atTick": 1680,
        "velocity": 0.42,
        "durationTicks": 240
      }
    ]
  },
  "bass-el-funk-one-bar__funk": {
    "id": "bass-el-funk-one-bar__funk",
    "style": "funk",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.84,
        "durationTicks": 480
      },
      {
        "sound": "muted",
        "atTick": 240,
        "velocity": 0.38,
        "durationTicks": 240
      },
      {
        "sound": "muted",
        "atTick": 720,
        "velocity": 0.42,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.74,
        "durationTicks": 480
      },
      {
        "sound": "stac",
        "atTick": 1200,
        "velocity": 0.56,
        "durationTicks": 240
      },
      {
        "sound": "muted",
        "atTick": 1560,
        "velocity": 0.36,
        "durationTicks": 120
      },
      {
        "sound": "regular",
        "atTick": 1680,
        "velocity": 0.7,
        "durationTicks": 240
      }
    ]
  },
  "bass-el-funk-one-bar__latin": {
    "id": "bass-el-funk-one-bar__latin",
    "style": "latin",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.84,
        "durationTicks": 480
      },
      {
        "sound": "muted",
        "atTick": 240,
        "velocity": 0.38,
        "durationTicks": 240
      },
      {
        "sound": "muted",
        "atTick": 720,
        "velocity": 0.42,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.74,
        "durationTicks": 480
      },
      {
        "sound": "stac",
        "atTick": 1200,
        "velocity": 0.56,
        "durationTicks": 240
      },
      {
        "sound": "muted",
        "atTick": 1560,
        "velocity": 0.36,
        "durationTicks": 120
      },
      {
        "sound": "regular",
        "atTick": 1680,
        "velocity": 0.7,
        "durationTicks": 240
      }
    ]
  },
  "bass-el-funk-16th-chatter__funk": {
    "id": "bass-el-funk-16th-chatter__funk",
    "style": "funk",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.84,
        "durationTicks": 240
      },
      {
        "sound": "muted",
        "atTick": 240,
        "velocity": 0.34,
        "durationTicks": 120
      },
      {
        "sound": "muted",
        "atTick": 600,
        "velocity": 0.36,
        "durationTicks": 120
      },
      {
        "sound": "stac",
        "atTick": 720,
        "velocity": 0.58,
        "durationTicks": 240
      },
      {
        "sound": "muted",
        "atTick": 960,
        "velocity": 0.36,
        "durationTicks": 120
      },
      {
        "sound": "regular",
        "atTick": 1200,
        "velocity": 0.72,
        "durationTicks": 240
      },
      {
        "sound": "muted",
        "atTick": 1320,
        "velocity": 0.32,
        "durationTicks": 60
      },
      {
        "sound": "muted",
        "atTick": 1560,
        "velocity": 0.34,
        "durationTicks": 120
      },
      {
        "sound": "stac",
        "atTick": 1680,
        "velocity": 0.56,
        "durationTicks": 240
      }
    ]
  },
  "bass-el-funk-16th-chatter__latin": {
    "id": "bass-el-funk-16th-chatter__latin",
    "style": "latin",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.84,
        "durationTicks": 240
      },
      {
        "sound": "muted",
        "atTick": 240,
        "velocity": 0.34,
        "durationTicks": 120
      },
      {
        "sound": "muted",
        "atTick": 600,
        "velocity": 0.36,
        "durationTicks": 120
      },
      {
        "sound": "stac",
        "atTick": 720,
        "velocity": 0.58,
        "durationTicks": 240
      },
      {
        "sound": "muted",
        "atTick": 960,
        "velocity": 0.36,
        "durationTicks": 120
      },
      {
        "sound": "regular",
        "atTick": 1200,
        "velocity": 0.72,
        "durationTicks": 240
      },
      {
        "sound": "muted",
        "atTick": 1320,
        "velocity": 0.32,
        "durationTicks": 60
      },
      {
        "sound": "muted",
        "atTick": 1560,
        "velocity": 0.34,
        "durationTicks": 120
      },
      {
        "sound": "stac",
        "atTick": 1680,
        "velocity": 0.56,
        "durationTicks": 240
      }
    ]
  },
  "bass-el-funk-stab__funk": {
    "id": "bass-el-funk-stab__funk",
    "style": "funk",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.82,
        "durationTicks": 240
      },
      {
        "sound": "stac",
        "atTick": 240,
        "velocity": 0.62,
        "durationTicks": 240
      },
      {
        "sound": "muted",
        "atTick": 720,
        "velocity": 0.38,
        "durationTicks": 120
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.74,
        "durationTicks": 480
      },
      {
        "sound": "stac",
        "atTick": 1680,
        "velocity": 0.6,
        "durationTicks": 240
      }
    ]
  },
  "bass-el-funk-stab__latin": {
    "id": "bass-el-funk-stab__latin",
    "style": "latin",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.82,
        "durationTicks": 240
      },
      {
        "sound": "stac",
        "atTick": 240,
        "velocity": 0.62,
        "durationTicks": 240
      },
      {
        "sound": "muted",
        "atTick": 720,
        "velocity": 0.38,
        "durationTicks": 120
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.74,
        "durationTicks": 480
      },
      {
        "sound": "stac",
        "atTick": 1680,
        "velocity": 0.6,
        "durationTicks": 240
      }
    ]
  },
  "bass-el-funk-release__funk": {
    "id": "bass-el-funk-release__funk",
    "style": "funk",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.8,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 480,
        "velocity": 0.7,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.74,
        "durationTicks": 480
      },
      {
        "sound": "rel",
        "atTick": 1440,
        "velocity": 0.66,
        "durationTicks": 480
      }
    ]
  },
  "bass-el-funk-release__latin": {
    "id": "bass-el-funk-release__latin",
    "style": "latin",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.8,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 480,
        "velocity": 0.7,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.74,
        "durationTicks": 480
      },
      {
        "sound": "rel",
        "atTick": 1440,
        "velocity": 0.66,
        "durationTicks": 480
      }
    ]
  },
  "bass-el-funk-two-bar__funk": {
    "id": "bass-el-funk-two-bar__funk",
    "style": "funk",
    "bars": 2,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.82,
        "durationTicks": 480
      },
      {
        "sound": "muted",
        "atTick": 240,
        "velocity": 0.38,
        "durationTicks": 240
      },
      {
        "sound": "muted",
        "atTick": 720,
        "velocity": 0.4,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.74,
        "durationTicks": 480
      },
      {
        "sound": "muted",
        "atTick": 1680,
        "velocity": 0.4,
        "durationTicks": 240
      },
      {
        "sound": "stac",
        "atTick": 1920,
        "velocity": 0.62,
        "durationTicks": 240
      },
      {
        "sound": "muted",
        "atTick": 2160,
        "velocity": 0.36,
        "durationTicks": 120
      },
      {
        "sound": "stac",
        "atTick": 2400,
        "velocity": 0.6,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 2880,
        "velocity": 0.76,
        "durationTicks": 480
      },
      {
        "sound": "rel",
        "atTick": 3360,
        "velocity": 0.66,
        "durationTicks": 480
      }
    ]
  },
  "bass-el-funk-two-bar__latin": {
    "id": "bass-el-funk-two-bar__latin",
    "style": "latin",
    "bars": 2,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.82,
        "durationTicks": 480
      },
      {
        "sound": "muted",
        "atTick": 240,
        "velocity": 0.38,
        "durationTicks": 240
      },
      {
        "sound": "muted",
        "atTick": 720,
        "velocity": 0.4,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.74,
        "durationTicks": 480
      },
      {
        "sound": "muted",
        "atTick": 1680,
        "velocity": 0.4,
        "durationTicks": 240
      },
      {
        "sound": "stac",
        "atTick": 1920,
        "velocity": 0.62,
        "durationTicks": 240
      },
      {
        "sound": "muted",
        "atTick": 2160,
        "velocity": 0.36,
        "durationTicks": 120
      },
      {
        "sound": "stac",
        "atTick": 2400,
        "velocity": 0.6,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 2880,
        "velocity": 0.76,
        "durationTicks": 480
      },
      {
        "sound": "rel",
        "atTick": 3360,
        "velocity": 0.66,
        "durationTicks": 480
      }
    ]
  },
  "bass-el-latin-montuno__funk": {
    "id": "bass-el-latin-montuno__funk",
    "style": "funk",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.8,
        "durationTicks": 720
      },
      {
        "sound": "stac",
        "atTick": 720,
        "velocity": 0.66,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.74,
        "durationTicks": 480
      }
    ]
  },
  "bass-el-latin-montuno__latin": {
    "id": "bass-el-latin-montuno__latin",
    "style": "latin",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.8,
        "durationTicks": 720
      },
      {
        "sound": "stac",
        "atTick": 720,
        "velocity": 0.66,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.74,
        "durationTicks": 480
      }
    ]
  },
  "bass-el-latin-montuno-octave__funk": {
    "id": "bass-el-latin-montuno-octave__funk",
    "style": "funk",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.8,
        "durationTicks": 720
      },
      {
        "sound": "stac",
        "atTick": 720,
        "velocity": 0.66,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.72,
        "durationTicks": 480
      },
      {
        "sound": "stac",
        "atTick": 1440,
        "velocity": 0.62,
        "durationTicks": 240
      }
    ]
  },
  "bass-el-latin-montuno-octave__latin": {
    "id": "bass-el-latin-montuno-octave__latin",
    "style": "latin",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.8,
        "durationTicks": 720
      },
      {
        "sound": "stac",
        "atTick": 720,
        "velocity": 0.66,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.72,
        "durationTicks": 480
      },
      {
        "sound": "stac",
        "atTick": 1440,
        "velocity": 0.62,
        "durationTicks": 240
      }
    ]
  },
  "bass-el-latin-montuno-dense__funk": {
    "id": "bass-el-latin-montuno-dense__funk",
    "style": "funk",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.8,
        "durationTicks": 480
      },
      {
        "sound": "stac",
        "atTick": 720,
        "velocity": 0.64,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.74,
        "durationTicks": 480
      },
      {
        "sound": "stac",
        "atTick": 1200,
        "velocity": 0.56,
        "durationTicks": 240
      },
      {
        "sound": "stac",
        "atTick": 1680,
        "velocity": 0.6,
        "durationTicks": 240
      }
    ]
  },
  "bass-el-latin-montuno-dense__latin": {
    "id": "bass-el-latin-montuno-dense__latin",
    "style": "latin",
    "bars": 1,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.8,
        "durationTicks": 480
      },
      {
        "sound": "stac",
        "atTick": 720,
        "velocity": 0.64,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.74,
        "durationTicks": 480
      },
      {
        "sound": "stac",
        "atTick": 1200,
        "velocity": 0.56,
        "durationTicks": 240
      },
      {
        "sound": "stac",
        "atTick": 1680,
        "velocity": 0.6,
        "durationTicks": 240
      }
    ]
  },
  "bass-el-latin-2-3-clave__funk": {
    "id": "bass-el-latin-2-3-clave__funk",
    "style": "funk",
    "bars": 2,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.8,
        "durationTicks": 720
      },
      {
        "sound": "stac",
        "atTick": 720,
        "velocity": 0.64,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.74,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 1920,
        "velocity": 0.8,
        "durationTicks": 480
      },
      {
        "sound": "stac",
        "atTick": 2400,
        "velocity": 0.66,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 2640,
        "velocity": 0.7,
        "durationTicks": 240
      },
      {
        "sound": "stac",
        "atTick": 3360,
        "velocity": 0.62,
        "durationTicks": 240
      }
    ]
  },
  "bass-el-latin-2-3-clave__latin": {
    "id": "bass-el-latin-2-3-clave__latin",
    "style": "latin",
    "bars": 2,
    "atoms": [
      {
        "sound": "regular",
        "atTick": 0,
        "velocity": 0.8,
        "durationTicks": 720
      },
      {
        "sound": "stac",
        "atTick": 720,
        "velocity": 0.64,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 960,
        "velocity": 0.74,
        "durationTicks": 480
      },
      {
        "sound": "regular",
        "atTick": 1920,
        "velocity": 0.8,
        "durationTicks": 480
      },
      {
        "sound": "stac",
        "atTick": 2400,
        "velocity": 0.66,
        "durationTicks": 240
      },
      {
        "sound": "regular",
        "atTick": 2640,
        "velocity": 0.7,
        "durationTicks": 240
      },
      {
        "sound": "stac",
        "atTick": 3360,
        "velocity": 0.62,
        "durationTicks": 240
      }
    ]
  }
};
