/* AUTO-GENERATED by the Constructor "Опубликовать в код" action. Do not edit by hand.
 * When non-empty, this map fully replaces the base definitions. */
export const GENERATED_BASS_ORGANISMS: Record<string, unknown> = {
  "bass-up-swing-slow-org": {
    "id": "bass-up-swing-slow-org",
    "style": "swing",
    "label": "Swing Slow (половинки)",
    "sectionMap": {
      "intro": [
        "bass-up-swing-slow"
      ],
      "verseA": [
        "bass-up-swing-slow"
      ],
      "verseB": [
        "bass-up-swing-slow"
      ],
      "verseC": [
        "bass-up-swing-slow"
      ],
      "chorus": [
        "bass-up-swing-slow"
      ],
      "bridge": [
        "bass-up-swing-slow"
      ],
      "solo": [
        "bass-up-swing-slow"
      ],
      "ending": [
        "bass-up-swing-slow"
      ]
    }
  },
  "bass-up-swing-walking-org": {
    "id": "bass-up-swing-walking-org",
    "style": "swing",
    "label": "Swing Walking (четверти)",
    "sectionMap": {
      "intro": [
        "bass-up-swing-walking"
      ],
      "verseA": [
        "bass-up-swing-walking"
      ],
      "verseB": [
        "bass-up-swing-walking"
      ],
      "verseC": [
        "bass-up-swing-walking"
      ],
      "chorus": [
        "bass-up-swing-walking"
      ],
      "bridge": [
        "bass-up-swing-walking"
      ],
      "solo": [
        "bass-up-swing-walking"
      ],
      "ending": [
        "bass-up-swing-walking"
      ]
    }
  },
  "bass-up-swing-dense-org": {
    "id": "bass-up-swing-dense-org",
    "style": "swing",
    "label": "Swing Dense (восьмые)",
    "sectionMap": {
      "intro": [
        "bass-up-swing-dense"
      ],
      "verseA": [
        "bass-up-swing-dense"
      ],
      "verseB": [
        "bass-up-swing-dense"
      ],
      "verseC": [
        "bass-up-swing-dense"
      ],
      "chorus": [
        "bass-up-swing-dense"
      ],
      "bridge": [
        "bass-up-swing-dense"
      ],
      "solo": [
        "bass-up-swing-dense"
      ],
      "ending": [
        "bass-up-swing-dense"
      ]
    }
  },
  "bass-up-swing-max-org": {
    "id": "bass-up-swing-max-org",
    "style": "swing",
    "label": "Swing Max (триоли + bebop)",
    "sectionMap": {
      "intro": [
        "bass-up-swing-max"
      ],
      "verseA": [
        "bass-up-swing-max"
      ],
      "verseB": [
        "bass-up-swing-max"
      ],
      "verseC": [
        "bass-up-swing-max"
      ],
      "chorus": [
        "bass-up-swing-max"
      ],
      "bridge": [
        "bass-up-swing-max"
      ],
      "solo": [
        "bass-up-swing-max"
      ],
      "ending": [
        "bass-up-swing-max"
      ]
    }
  },
  "bass-up-bossa-org": {
    "id": "bass-up-bossa-org",
    "style": "bossa",
    "label": "Upright Bossa Root-5th",
    "sectionMap": {
      "intro": [
        "bass-up-bossa-sparse"
      ],
      "verseA": [
        "bass-up-bossa-sparse"
      ],
      "verseB": [
        "bass-up-bossa-sparse"
      ],
      "verseC": [
        "bass-up-bossa-sparse"
      ],
      "chorus": [
        "bass-up-bossa-medium"
      ],
      "bridge": [
        "bass-up-bossa-sparse"
      ],
      "solo": [
        "bass-up-bossa-medium"
      ],
      "ending": [
        "bass-up-bossa-sparse"
      ]
    }
  },
  "bass-up-ballad-org": {
    "id": "bass-up-ballad-org",
    "style": "ballad",
    "label": "Upright Ballad Two-Feel",
    "sectionMap": {
      "intro": [
        "bass-up-ballad-sparse"
      ],
      "verseA": [
        "bass-up-ballad-sparse"
      ],
      "verseB": [
        "bass-up-ballad-sparse"
      ],
      "verseC": [
        "bass-up-ballad-sparse"
      ],
      "chorus": [
        "bass-up-ballad-medium"
      ],
      "bridge": [
        "bass-up-ballad-sparse"
      ],
      "solo": [
        "bass-up-ballad-medium"
      ],
      "ending": [
        "bass-up-ballad-sparse"
      ]
    }
  },
  "bass-el-funk-org": {
    "id": "bass-el-funk-org",
    "style": "funk",
    "label": "Electric Funk Pocket",
    "sectionMap": {
      "intro": [
        "bass-el-funk-sparse"
      ],
      "verseA": [
        "bass-el-funk-sparse"
      ],
      "verseB": [
        "bass-el-funk-sparse"
      ],
      "verseC": [
        "bass-el-funk-sparse"
      ],
      "chorus": [
        "bass-el-funk-medium"
      ],
      "bridge": [
        "bass-el-funk-sparse"
      ],
      "solo": [
        "bass-el-funk-medium"
      ],
      "ending": [
        "bass-el-funk-sparse"
      ]
    }
  },
  "bass-el-funk-dense-org": {
    "id": "bass-el-funk-dense-org",
    "style": "funk",
    "label": "Electric Funk Dense",
    "sectionMap": {
      "intro": [
        "bass-el-funk-medium"
      ],
      "verseA": [
        "bass-el-funk-medium"
      ],
      "verseB": [
        "bass-el-funk-medium"
      ],
      "verseC": [
        "bass-el-funk-medium"
      ],
      "chorus": [
        "bass-el-funk-dense"
      ],
      "bridge": [
        "bass-el-funk-medium"
      ],
      "solo": [
        "bass-el-funk-dense"
      ],
      "ending": [
        "bass-el-funk-medium"
      ]
    }
  },
  "bass-el-latin-org": {
    "id": "bass-el-latin-org",
    "style": "latin",
    "label": "Electric Latin Montuno",
    "sectionMap": {
      "intro": [
        "bass-el-latin-sparse"
      ],
      "verseA": [
        "bass-el-latin-sparse"
      ],
      "verseB": [
        "bass-el-latin-sparse"
      ],
      "verseC": [
        "bass-el-latin-sparse"
      ],
      "chorus": [
        "bass-el-latin-medium"
      ],
      "bridge": [
        "bass-el-latin-sparse"
      ],
      "solo": [
        "bass-el-latin-medium"
      ],
      "ending": [
        "bass-el-latin-sparse"
      ]
    }
  },
  "bass-el-latin-dense-org": {
    "id": "bass-el-latin-dense-org",
    "style": "latin",
    "label": "Electric Latin Dense",
    "sectionMap": {
      "intro": [
        "bass-el-latin-medium"
      ],
      "verseA": [
        "bass-el-latin-medium"
      ],
      "verseB": [
        "bass-el-latin-medium"
      ],
      "verseC": [
        "bass-el-latin-medium"
      ],
      "chorus": [
        "bass-el-latin-dense"
      ],
      "bridge": [
        "bass-el-latin-medium"
      ],
      "solo": [
        "bass-el-latin-dense"
      ],
      "ending": [
        "bass-el-latin-medium"
      ]
    }
  }
};
