/* AUTO-GENERATED by the Constructor "Опубликовать в код" action. Do not edit by hand.
 * When non-empty, this map fully replaces the base definitions. */
export const GENERATED_BASS_CELLS: Record<string, unknown> = {
  "bass-up-swing-slow": {
    "id": "bass-up-swing-slow",
    "style": "swing",
    "length": 8,
    "timeSignature": [
      4,
      4
    ],
    "lanes": [
      {
        "name": "bass",
        "probability": 1,
        "clips": [
          {
            "startBar": 0,
            "lengthBars": 2,
            "pool": [
              "bass-up-swing-walk-half-note__swing"
            ]
          },
          {
            "startBar": 2,
            "lengthBars": 2,
            "pool": [
              "bass-up-swing-walk-half-note__swing"
            ]
          },
          {
            "startBar": 4,
            "lengthBars": 2,
            "pool": [
              "bass-up-swing-walk-half-note__swing"
            ]
          },
          {
            "startBar": 6,
            "lengthBars": 2,
            "pool": [
              "bass-up-swing-walk-half-note__swing"
            ]
          }
        ]
      }
    ]
  },
  "bass-up-swing-walking": {
    "id": "bass-up-swing-walking",
    "style": "swing",
    "length": 8,
    "timeSignature": [
      4,
      4
    ],
    "lanes": [
      {
        "name": "bass",
        "probability": 1,
        "clips": [
          {
            "startBar": 0,
            "lengthBars": 2,
            "pool": [
              "bass-up-swing-walk-chromatic__swing"
            ]
          },
          {
            "startBar": 2,
            "lengthBars": 2,
            "pool": [
              "bass-up-swing-walk-chromatic__swing"
            ]
          },
          {
            "startBar": 4,
            "lengthBars": 2,
            "pool": [
              "bass-up-swing-walk-chromatic__swing"
            ]
          },
          {
            "startBar": 6,
            "lengthBars": 2,
            "pool": [
              "bass-up-swing-walk-chromatic__swing"
            ]
          }
        ]
      }
    ]
  },
  "bass-up-swing-dense": {
    "id": "bass-up-swing-dense",
    "style": "swing",
    "length": 8,
    "timeSignature": [
      4,
      4
    ],
    "lanes": [
      {
        "name": "bass",
        "probability": 1,
        "clips": [
          {
            "startBar": 0,
            "lengthBars": 2,
            "pool": [
              "bass-up-swing-walk-8th__swing"
            ]
          },
          {
            "startBar": 2,
            "lengthBars": 2,
            "pool": [
              "bass-up-swing-walk-8th__swing"
            ]
          },
          {
            "startBar": 4,
            "lengthBars": 2,
            "pool": [
              "bass-up-swing-walk-8th__swing"
            ]
          },
          {
            "startBar": 6,
            "lengthBars": 2,
            "pool": [
              "bass-up-swing-walk-8th__swing"
            ]
          }
        ]
      }
    ]
  },
  "bass-up-swing-max": {
    "id": "bass-up-swing-max",
    "style": "swing",
    "length": 8,
    "timeSignature": [
      4,
      4
    ],
    "lanes": [
      {
        "name": "bass",
        "probability": 1,
        "clips": [
          {
            "startBar": 0,
            "lengthBars": 2,
            "pool": [
              "bass-up-swing-walk-triplet__swing",
              "bass-up-swing-walk-8th__swing"
            ]
          },
          {
            "startBar": 2,
            "lengthBars": 2,
            "pool": [
              "bass-up-swing-walk-2bar-chromatic__swing"
            ]
          },
          {
            "startBar": 4,
            "lengthBars": 2,
            "pool": [
              "bass-up-swing-walk-8th-ghost__swing",
              "bass-up-swing-walk-bebop__swing"
            ]
          },
          {
            "startBar": 6,
            "lengthBars": 2,
            "pool": [
              "bass-up-swing-walk-triplet__swing",
              "bass-up-swing-bebop-turnaround__swing"
            ]
          }
        ]
      }
    ]
  },
  "bass-up-bossa-sparse": {
    "id": "bass-up-bossa-sparse",
    "style": "bossa",
    "length": 8,
    "timeSignature": [
      4,
      4
    ],
    "lanes": [
      {
        "name": "bass",
        "probability": 1,
        "clips": [
          {
            "startBar": 0,
            "lengthBars": 2,
            "pool": [
              "bass-up-bossa-1-5__bossa"
            ]
          },
          {
            "startBar": 2,
            "lengthBars": 2,
            "pool": [
              "bass-up-bossa-1-5__bossa"
            ]
          },
          {
            "startBar": 4,
            "lengthBars": 2,
            "pool": [
              "bass-up-bossa-1-5__bossa"
            ]
          },
          {
            "startBar": 6,
            "lengthBars": 2,
            "pool": [
              "bass-up-bossa-1-5__bossa",
              "bass-up-bossa-approach__bossa"
            ]
          }
        ]
      }
    ]
  },
  "bass-up-bossa-medium": {
    "id": "bass-up-bossa-medium",
    "style": "bossa",
    "length": 8,
    "timeSignature": [
      4,
      4
    ],
    "lanes": [
      {
        "name": "bass",
        "probability": 1,
        "clips": [
          {
            "startBar": 0,
            "lengthBars": 2,
            "pool": [
              "bass-up-bossa-1-5-octave__bossa",
              "bass-up-bossa-1-5__bossa"
            ]
          },
          {
            "startBar": 2,
            "lengthBars": 2,
            "pool": [
              "bass-up-bossa-1-5__bossa",
              "bass-up-bossa-1-5-octave__bossa"
            ]
          },
          {
            "startBar": 4,
            "lengthBars": 2,
            "pool": [
              "bass-up-bossa-1-5-octave__bossa",
              "bass-up-bossa-1-5__bossa"
            ]
          },
          {
            "startBar": 6,
            "lengthBars": 2,
            "pool": [
              "bass-up-bossa-1-5__bossa",
              "bass-up-bossa-approach__bossa"
            ]
          }
        ]
      }
    ]
  },
  "bass-up-ballad-sparse": {
    "id": "bass-up-ballad-sparse",
    "style": "ballad",
    "length": 8,
    "timeSignature": [
      4,
      4
    ],
    "lanes": [
      {
        "name": "bass",
        "probability": 1,
        "clips": [
          {
            "startBar": 0,
            "lengthBars": 2,
            "pool": [
              "bass-up-ballad-two-feel__ballad"
            ]
          },
          {
            "startBar": 2,
            "lengthBars": 2,
            "pool": [
              "bass-up-ballad-two-feel__ballad"
            ]
          },
          {
            "startBar": 4,
            "lengthBars": 2,
            "pool": [
              "bass-up-ballad-two-feel__ballad"
            ]
          },
          {
            "startBar": 6,
            "lengthBars": 2,
            "pool": [
              "bass-up-ballad-two-feel__ballad",
              "bass-up-ballad-half-note-walk__ballad"
            ]
          }
        ]
      }
    ]
  },
  "bass-up-ballad-medium": {
    "id": "bass-up-ballad-medium",
    "style": "ballad",
    "length": 8,
    "timeSignature": [
      4,
      4
    ],
    "lanes": [
      {
        "name": "bass",
        "probability": 1,
        "clips": [
          {
            "startBar": 0,
            "lengthBars": 2,
            "pool": [
              "bass-up-ballad-two-feel-5__ballad",
              "bass-up-ballad-two-feel__ballad"
            ]
          },
          {
            "startBar": 2,
            "lengthBars": 2,
            "pool": [
              "bass-up-ballad-two-feel__ballad",
              "bass-up-ballad-two-feel-5__ballad"
            ]
          },
          {
            "startBar": 4,
            "lengthBars": 2,
            "pool": [
              "bass-up-ballad-two-feel-5__ballad",
              "bass-up-ballad-approach__ballad"
            ]
          },
          {
            "startBar": 6,
            "lengthBars": 2,
            "pool": [
              "bass-up-ballad-two-feel__ballad",
              "bass-up-ballad-half-note-walk__ballad"
            ]
          }
        ]
      }
    ]
  },
  "bass-el-funk-sparse": {
    "id": "bass-el-funk-sparse",
    "style": "funk",
    "length": 8,
    "timeSignature": [
      4,
      4
    ],
    "lanes": [
      {
        "name": "bass",
        "probability": 1,
        "clips": [
          {
            "startBar": 0,
            "lengthBars": 2,
            "pool": [
              "bass-el-funk-pocket__funk"
            ]
          },
          {
            "startBar": 2,
            "lengthBars": 2,
            "pool": [
              "bass-el-funk-pocket__funk"
            ]
          },
          {
            "startBar": 4,
            "lengthBars": 2,
            "pool": [
              "bass-el-funk-pocket__funk"
            ]
          },
          {
            "startBar": 6,
            "lengthBars": 2,
            "pool": [
              "bass-el-funk-pocket__funk",
              "bass-el-funk-release__funk"
            ]
          }
        ]
      }
    ]
  },
  "bass-el-funk-medium": {
    "id": "bass-el-funk-medium",
    "style": "funk",
    "length": 8,
    "timeSignature": [
      4,
      4
    ],
    "lanes": [
      {
        "name": "bass",
        "probability": 1,
        "clips": [
          {
            "startBar": 0,
            "lengthBars": 2,
            "pool": [
              "bass-el-funk-one-bar__funk",
              "bass-el-funk-pocket__funk"
            ]
          },
          {
            "startBar": 2,
            "lengthBars": 2,
            "pool": [
              "bass-el-funk-stab__funk",
              "bass-el-funk-one-bar__funk"
            ]
          },
          {
            "startBar": 4,
            "lengthBars": 2,
            "pool": [
              "bass-el-funk-pocket__funk",
              "bass-el-funk-stab__funk"
            ]
          },
          {
            "startBar": 6,
            "lengthBars": 2,
            "pool": [
              "bass-el-funk-one-bar__funk",
              "bass-el-funk-release__funk"
            ]
          }
        ]
      }
    ]
  },
  "bass-el-funk-dense": {
    "id": "bass-el-funk-dense",
    "style": "funk",
    "length": 8,
    "timeSignature": [
      4,
      4
    ],
    "lanes": [
      {
        "name": "bass",
        "probability": 1,
        "clips": [
          {
            "startBar": 0,
            "lengthBars": 2,
            "pool": [
              "bass-el-funk-16th-chatter__funk",
              "bass-el-funk-one-bar__funk"
            ]
          },
          {
            "startBar": 2,
            "lengthBars": 2,
            "pool": [
              "bass-el-funk-two-bar__funk"
            ]
          },
          {
            "startBar": 4,
            "lengthBars": 2,
            "pool": [
              "bass-el-funk-16th-chatter__funk",
              "bass-el-funk-stab__funk"
            ]
          },
          {
            "startBar": 6,
            "lengthBars": 2,
            "pool": [
              "bass-el-funk-one-bar__funk",
              "bass-el-funk-release__funk"
            ]
          }
        ]
      }
    ]
  },
  "bass-el-latin-sparse": {
    "id": "bass-el-latin-sparse",
    "style": "latin",
    "length": 8,
    "timeSignature": [
      4,
      4
    ],
    "lanes": [
      {
        "name": "bass",
        "probability": 1,
        "clips": [
          {
            "startBar": 0,
            "lengthBars": 2,
            "pool": [
              "bass-el-latin-montuno__latin"
            ]
          },
          {
            "startBar": 2,
            "lengthBars": 2,
            "pool": [
              "bass-el-latin-montuno__latin"
            ]
          },
          {
            "startBar": 4,
            "lengthBars": 2,
            "pool": [
              "bass-el-latin-montuno__latin"
            ]
          },
          {
            "startBar": 6,
            "lengthBars": 2,
            "pool": [
              "bass-el-latin-montuno__latin"
            ]
          }
        ]
      }
    ]
  },
  "bass-el-latin-medium": {
    "id": "bass-el-latin-medium",
    "style": "latin",
    "length": 8,
    "timeSignature": [
      4,
      4
    ],
    "lanes": [
      {
        "name": "bass",
        "probability": 1,
        "clips": [
          {
            "startBar": 0,
            "lengthBars": 2,
            "pool": [
              "bass-el-latin-montuno-octave__latin",
              "bass-el-latin-montuno__latin"
            ]
          },
          {
            "startBar": 2,
            "lengthBars": 2,
            "pool": [
              "bass-el-latin-2-3-clave__latin"
            ]
          },
          {
            "startBar": 4,
            "lengthBars": 2,
            "pool": [
              "bass-el-latin-montuno-octave__latin",
              "bass-el-latin-montuno__latin"
            ]
          },
          {
            "startBar": 6,
            "lengthBars": 2,
            "pool": [
              "bass-el-latin-montuno-dense__latin",
              "bass-el-latin-2-3-clave__latin"
            ]
          }
        ]
      }
    ]
  },
  "bass-el-latin-dense": {
    "id": "bass-el-latin-dense",
    "style": "latin",
    "length": 8,
    "timeSignature": [
      4,
      4
    ],
    "lanes": [
      {
        "name": "bass",
        "probability": 1,
        "clips": [
          {
            "startBar": 0,
            "lengthBars": 2,
            "pool": [
              "bass-el-latin-montuno-dense__latin",
              "bass-el-latin-montuno-octave__latin"
            ]
          },
          {
            "startBar": 2,
            "lengthBars": 2,
            "pool": [
              "bass-el-latin-2-3-clave__latin"
            ]
          },
          {
            "startBar": 4,
            "lengthBars": 2,
            "pool": [
              "bass-el-latin-montuno-dense__latin",
              "bass-el-latin-montuno__latin"
            ]
          },
          {
            "startBar": 6,
            "lengthBars": 2,
            "pool": [
              "bass-el-latin-montuno-dense__latin",
              "bass-el-latin-2-3-clave__latin"
            ]
          }
        ]
      }
    ]
  }
};
