/* AUTO-GENERATED by the Constructor "Опубликовать в код" action. Do not edit by hand.
 * When non-empty, this map fully replaces the base definitions. */
export const GENERATED_DRUM_ORGANISMS: Record<string, unknown> = {
  "swing-default": {
    "id": "swing-default",
    "style": "swing",
    "label": "Swing Default (все секции, щётки)",
    "sectionMap": {
      "intro": [
        "swing-8-intro"
      ],
      "verseA": [
        "swing-16-brushes",
        "swing-16-verse",
        "swing-16-brushes-sync",
        "swing-16-bridge"
      ],
      "bridge": [
        "swing-16-bridge"
      ],
      "verseB": [
        "swing-16-brushes-comp"
      ],
      "verseC": [
        "swing-16-verse",
        "swing-16-brushes"
      ],
      "chorus": [
        "swing-16-chorus"
      ],
      "solo": [
        "swing-16-solo"
      ],
      "ending": [
        "swing-8-ending"
      ]
    },
    "timeSignatureOverrides": {
      "3/4": {
        "verseA": [
          "swing-waltz-12-verse"
        ],
        "bridge": [
          "swing-waltz-12-bridge"
        ],
        "chorus": [
          "swing-waltz-12-chorus"
        ]
      }
    },
    "defaultForm": [
      {
        "label": "intro",
        "type": "intro",
        "cellPool": [
          "swing-8-intro"
        ],
        "repeats": 1
      },
      {
        "label": "verseA",
        "type": "verseA",
        "cellPool": [
          "swing-16-brushes",
          "swing-16-verse"
        ],
        "repeats": 1
      },
      {
        "label": "bridge",
        "type": "bridge",
        "cellPool": [
          "swing-16-bridge"
        ],
        "repeats": 1
      },
      {
        "label": "verseB",
        "type": "verseB",
        "cellPool": [
          "swing-16-brushes-comp"
        ],
        "repeats": 1
      },
      {
        "label": "verseC",
        "type": "verseC",
        "cellPool": [
          "swing-16-verse",
          "swing-16-brushes"
        ],
        "repeats": 1
      },
      {
        "label": "chorus",
        "type": "chorus",
        "cellPool": [
          "swing-16-chorus"
        ],
        "repeats": 1
      },
      {
        "label": "solo",
        "type": "solo",
        "cellPool": [
          "swing-16-solo"
        ],
        "repeats": 1
      },
      {
        "label": "ending",
        "type": "ending",
        "cellPool": [
          "swing-8-ending"
        ],
        "repeats": 1
      }
    ]
  },
  "bossa-default": {
    "id": "bossa-default",
    "style": "bossa",
    "label": "Bossa Default (все секции, канонический)",
    "sectionMap": {
      "intro": [
        "bossa-8-intro"
      ],
      "verseA": [
        "bossa-16-verse",
        "bossa-16-verse-var"
      ],
      "bridge": [
        "bossa-16-bridge"
      ],
      "verseB": [
        "bossa-16-basic",
        "bossa-16-ghost"
      ],
      "verseC": [
        "bossa-16-verse",
        "bossa-16-verse-var"
      ],
      "chorus": [
        "bossa-16-chorus"
      ],
      "solo": [
        "bossa-16-solo"
      ],
      "ending": [
        "bossa-8-ending"
      ]
    },
    "defaultForm": [
      {
        "label": "intro",
        "type": "intro",
        "cellPool": [
          "bossa-8-intro"
        ],
        "repeats": 1
      },
      {
        "label": "verseA",
        "type": "verseA",
        "cellPool": [
          "bossa-16-verse",
          "bossa-16-verse-var"
        ],
        "repeats": 1
      },
      {
        "label": "bridge",
        "type": "bridge",
        "cellPool": [
          "bossa-16-bridge"
        ],
        "repeats": 1
      },
      {
        "label": "verseB",
        "type": "verseB",
        "cellPool": [
          "bossa-16-basic",
          "bossa-16-ghost"
        ],
        "repeats": 1
      },
      {
        "label": "verseC",
        "type": "verseC",
        "cellPool": [
          "bossa-16-verse",
          "bossa-16-verse-var"
        ],
        "repeats": 1
      },
      {
        "label": "chorus",
        "type": "chorus",
        "cellPool": [
          "bossa-16-chorus"
        ],
        "repeats": 1
      },
      {
        "label": "solo",
        "type": "solo",
        "cellPool": [
          "bossa-16-solo"
        ],
        "repeats": 1
      },
      {
        "label": "ending",
        "type": "ending",
        "cellPool": [
          "bossa-8-ending"
        ],
        "repeats": 1
      }
    ]
  },
  "funk-default": {
    "id": "funk-default",
    "style": "funk",
    "label": "Funk Default (все секции, канонический)",
    "sectionMap": {
      "intro": [
        "funk-8-intro"
      ],
      "verseA": [
        "funk-16-verse",
        "funk-16-verse-var"
      ],
      "bridge": [
        "funk-16-bridge"
      ],
      "verseB": [
        "funk-16-pocket",
        "funk-16-tight"
      ],
      "verseC": [
        "funk-16-verse",
        "funk-16-verse-var"
      ],
      "chorus": [
        "funk-16-chorus"
      ],
      "solo": [
        "funk-16-solo"
      ],
      "ending": [
        "funk-8-ending"
      ]
    },
    "defaultForm": [
      {
        "label": "intro",
        "type": "intro",
        "cellPool": [
          "funk-8-intro"
        ],
        "repeats": 1
      },
      {
        "label": "verseA",
        "type": "verseA",
        "cellPool": [
          "funk-16-verse",
          "funk-16-verse-var"
        ],
        "repeats": 1
      },
      {
        "label": "bridge",
        "type": "bridge",
        "cellPool": [
          "funk-16-bridge"
        ],
        "repeats": 1
      },
      {
        "label": "verseB",
        "type": "verseB",
        "cellPool": [
          "funk-16-pocket",
          "funk-16-tight"
        ],
        "repeats": 1
      },
      {
        "label": "verseC",
        "type": "verseC",
        "cellPool": [
          "funk-16-verse",
          "funk-16-verse-var"
        ],
        "repeats": 1
      },
      {
        "label": "chorus",
        "type": "chorus",
        "cellPool": [
          "funk-16-chorus"
        ],
        "repeats": 1
      },
      {
        "label": "solo",
        "type": "solo",
        "cellPool": [
          "funk-16-solo"
        ],
        "repeats": 1
      },
      {
        "label": "ending",
        "type": "ending",
        "cellPool": [
          "funk-8-ending"
        ],
        "repeats": 1
      }
    ]
  },
  "latin-default": {
    "id": "latin-default",
    "style": "latin",
    "label": "Latin Default (все секции, канонический)",
    "sectionMap": {
      "intro": [
        "latin-8-intro"
      ],
      "verseA": [
        "latin-16-verse",
        "latin-16-verse-var"
      ],
      "bridge": [
        "latin-16-bridge"
      ],
      "verseB": [
        "latin-16-montuno",
        "latin-16-verse-var"
      ],
      "verseC": [
        "latin-16-verse",
        "latin-16-verse-var"
      ],
      "chorus": [
        "latin-16-chorus"
      ],
      "solo": [
        "latin-16-solo"
      ],
      "ending": [
        "latin-8-ending"
      ]
    },
    "defaultForm": [
      {
        "label": "intro",
        "type": "intro",
        "cellPool": [
          "latin-8-intro"
        ],
        "repeats": 1
      },
      {
        "label": "verseA",
        "type": "verseA",
        "cellPool": [
          "latin-16-verse",
          "latin-16-verse-var"
        ],
        "repeats": 1
      },
      {
        "label": "bridge",
        "type": "bridge",
        "cellPool": [
          "latin-16-bridge"
        ],
        "repeats": 1
      },
      {
        "label": "verseB",
        "type": "verseB",
        "cellPool": [
          "latin-16-montuno",
          "latin-16-verse-var"
        ],
        "repeats": 1
      },
      {
        "label": "verseC",
        "type": "verseC",
        "cellPool": [
          "latin-16-verse",
          "latin-16-verse-var"
        ],
        "repeats": 1
      },
      {
        "label": "chorus",
        "type": "chorus",
        "cellPool": [
          "latin-16-chorus"
        ],
        "repeats": 1
      },
      {
        "label": "solo",
        "type": "solo",
        "cellPool": [
          "latin-16-solo"
        ],
        "repeats": 1
      },
      {
        "label": "ending",
        "type": "ending",
        "cellPool": [
          "latin-8-ending"
        ],
        "repeats": 1
      }
    ]
  },
  "ballad-default": {
    "id": "ballad-default",
    "style": "ballad",
    "label": "Ballad Default (все секции, канонический)",
    "sectionMap": {
      "intro": [
        "ballad-8-intro"
      ],
      "verseA": [
        "ballad-16-verse",
        "ballad-16-verse-var"
      ],
      "bridge": [
        "ballad-16-bridge"
      ],
      "verseB": [
        "ballad-16-texture",
        "ballad-16-verse-var"
      ],
      "verseC": [
        "ballad-16-verse",
        "ballad-16-verse-var"
      ],
      "chorus": [
        "ballad-16-chorus"
      ],
      "solo": [
        "ballad-16-solo"
      ],
      "ending": [
        "ballad-8-ending"
      ]
    },
    "defaultForm": [
      {
        "label": "intro",
        "type": "intro",
        "cellPool": [
          "ballad-8-intro"
        ],
        "repeats": 1
      },
      {
        "label": "verseA",
        "type": "verseA",
        "cellPool": [
          "ballad-16-verse",
          "ballad-16-verse-var"
        ],
        "repeats": 1
      },
      {
        "label": "bridge",
        "type": "bridge",
        "cellPool": [
          "ballad-16-bridge"
        ],
        "repeats": 1
      },
      {
        "label": "verseB",
        "type": "verseB",
        "cellPool": [
          "ballad-16-texture",
          "ballad-16-verse-var"
        ],
        "repeats": 1
      },
      {
        "label": "verseC",
        "type": "verseC",
        "cellPool": [
          "ballad-16-verse",
          "ballad-16-verse-var"
        ],
        "repeats": 1
      },
      {
        "label": "chorus",
        "type": "chorus",
        "cellPool": [
          "ballad-16-chorus"
        ],
        "repeats": 1
      },
      {
        "label": "solo",
        "type": "solo",
        "cellPool": [
          "ballad-16-solo"
        ],
        "repeats": 1
      },
      {
        "label": "ending",
        "type": "ending",
        "cellPool": [
          "ballad-8-ending"
        ],
        "repeats": 1
      }
    ]
  }
};
