/* AUTO-GENERATED by the Drum Constructor "Сохранить" action. Do not edit by hand.
 * When non-empty, this map fully replaces the base definitions. */
export const GENERATED_DRUM_ORGANISMS: Record<string, unknown> = {};
