/* AUTO-GENERATED by the Constructor "Опубликовать в код" action. Do not edit by hand.
 * When non-empty, this map fully replaces the base definitions. */
export const GENERATED_PIANO_CELLS: Record<string, unknown> = {
  "piano-swing-sparse": {
    "id": "piano-swing-sparse",
    "style": "swing",
    "length": 8,
    "timeSignature": [
      4,
      4
    ],
    "velocity": 0.8,
    "dynamics": {
      "type": "steady",
      "amount": 0
    },
    "lanes": [
      {
        "name": "comping",
        "probability": 1,
        "clips": [
          {
            "startBar": 0,
            "lengthBars": 2,
            "pool": [
              "piano-basie-2-4-swing",
              "piano-half-notes-swing",
              "piano-one-three-swing"
            ]
          },
          {
            "startBar": 2,
            "lengthBars": 2,
            "pool": [
              "piano-charleston-swing",
              "piano-offbeat-2-4-swing",
              "piano-basie-2-4-swing"
            ]
          },
          {
            "startBar": 4,
            "lengthBars": 2,
            "pool": [
              "piano-basie-2-4-swing",
              "piano-two-and-four-swing",
              "piano-half-notes-swing"
            ]
          },
          {
            "startBar": 6,
            "lengthBars": 2,
            "pool": [
              "piano-half-notes-swing",
              "piano-basie-2-4-swing",
              "piano-charleston-swing"
            ]
          }
        ]
      }
    ]
  },
  "piano-swing-medium": {
    "id": "piano-swing-medium",
    "style": "swing",
    "length": 8,
    "timeSignature": [
      4,
      4
    ],
    "velocity": 0.8,
    "dynamics": {
      "type": "steady",
      "amount": 0
    },
    "lanes": [
      {
        "name": "comping",
        "probability": 1,
        "clips": [
          {
            "startBar": 0,
            "lengthBars": 2,
            "pool": [
              "piano-charleston-swing",
              "piano-anticipation-push-swing",
              "piano-one-twoand-four-swing"
            ]
          },
          {
            "startBar": 2,
            "lengthBars": 2,
            "pool": [
              "piano-bossa-top-swing",
              "piano-garland-swing",
              "piano-charleston-swing"
            ]
          },
          {
            "startBar": 4,
            "lengthBars": 2,
            "pool": [
              "piano-garland-swing",
              "piano-anticipation-push-swing",
              "piano-offbeat-2-4-swing"
            ]
          },
          {
            "startBar": 6,
            "lengthBars": 2,
            "pool": [
              "piano-kelly-push-swing",
              "piano-bossa-top-swing",
              "piano-garland-swing"
            ]
          }
        ]
      }
    ]
  },
  "piano-swing-dense": {
    "id": "piano-swing-dense",
    "style": "swing",
    "length": 8,
    "timeSignature": [
      4,
      4
    ],
    "velocity": 0.8,
    "dynamics": {
      "type": "steady",
      "amount": 0
    },
    "lanes": [
      {
        "name": "comping",
        "probability": 1,
        "clips": [
          {
            "startBar": 0,
            "lengthBars": 2,
            "pool": [
              "piano-walking-comp-swing",
              "piano-full-comp-swing",
              "piano-shout-swing"
            ]
          },
          {
            "startBar": 2,
            "lengthBars": 2,
            "pool": [
              "piano-quarter-notes-swing",
              "piano-walking-comp-swing",
              "piano-full-comp-swing"
            ]
          },
          {
            "startBar": 4,
            "lengthBars": 2,
            "pool": [
              "piano-shout-swing",
              "piano-full-comp-swing",
              "piano-walking-comp-swing"
            ]
          },
          {
            "startBar": 6,
            "lengthBars": 2,
            "pool": [
              "piano-quarter-comp-swing",
              "piano-walking-comp-swing",
              "piano-full-comp-swing"
            ]
          }
        ]
      }
    ]
  },
  "piano-basie-light-swing": {
    "id": "piano-basie-light-swing",
    "style": "swing",
    "length": 8,
    "timeSignature": [
      4,
      4
    ],
    "velocity": 0.8,
    "dynamics": {
      "type": "steady",
      "amount": 0
    },
    "lanes": [
      {
        "name": "comping",
        "probability": 1,
        "clips": [
          {
            "startBar": 0,
            "lengthBars": 2,
            "pool": [
              "piano-basie-2-4-swing",
              "piano-twoand-only-swing",
              "piano-half-notes-swing"
            ]
          },
          {
            "startBar": 2,
            "lengthBars": 2,
            "pool": [
              "piano-rest-swing",
              "piano-basie-2-4-swing",
              "piano-twoand-only-swing"
            ]
          },
          {
            "startBar": 4,
            "lengthBars": 2,
            "pool": [
              "piano-basie-2-4-swing",
              "piano-half-notes-swing",
              "piano-twoand-only-swing"
            ]
          },
          {
            "startBar": 6,
            "lengthBars": 2,
            "pool": [
              "piano-twoand-only-swing",
              "piano-rest-swing",
              "piano-basie-2-4-swing"
            ]
          }
        ]
      }
    ]
  },
  "piano-offbeat-push-swing": {
    "id": "piano-offbeat-push-swing",
    "style": "swing",
    "length": 8,
    "timeSignature": [
      4,
      4
    ],
    "velocity": 0.8,
    "dynamics": {
      "type": "steady",
      "amount": 0
    },
    "lanes": [
      {
        "name": "comping",
        "probability": 1,
        "clips": [
          {
            "startBar": 0,
            "lengthBars": 2,
            "pool": [
              "piano-offbeat-2-4-swing",
              "piano-two-threeand-swing",
              "piano-anticipation-4and-swing"
            ]
          },
          {
            "startBar": 2,
            "lengthBars": 2,
            "pool": [
              "piano-kelly-push-swing",
              "piano-offbeat-2-4-swing",
              "piano-anticipation-push-swing"
            ]
          },
          {
            "startBar": 4,
            "lengthBars": 2,
            "pool": [
              "piano-offbeat-2-4-swing",
              "piano-anticipation-4and-swing",
              "piano-two-threeand-swing"
            ]
          },
          {
            "startBar": 6,
            "lengthBars": 2,
            "pool": [
              "piano-anticipation-4and-swing",
              "piano-kelly-push-swing",
              "piano-offbeat-2-4-swing"
            ]
          }
        ]
      }
    ]
  },
  "piano-beginner-safe-swing": {
    "id": "piano-beginner-safe-swing",
    "style": "swing",
    "length": 8,
    "timeSignature": [
      4,
      4
    ],
    "velocity": 0.8,
    "dynamics": {
      "type": "steady",
      "amount": 0
    },
    "lanes": [
      {
        "name": "comping",
        "probability": 1,
        "clips": [
          {
            "startBar": 0,
            "lengthBars": 2,
            "pool": [
              "piano-half-notes-swing",
              "piano-whole-note-swing",
              "piano-half-notes-swing"
            ]
          },
          {
            "startBar": 2,
            "lengthBars": 2,
            "pool": [
              "piano-whole-note-swing",
              "piano-half-notes-swing",
              "piano-one-three-swing"
            ]
          },
          {
            "startBar": 4,
            "lengthBars": 2,
            "pool": [
              "piano-half-notes-swing",
              "piano-whole-note-swing",
              "piano-two-and-four-swing"
            ]
          },
          {
            "startBar": 6,
            "lengthBars": 2,
            "pool": [
              "piano-whole-note-swing",
              "piano-half-notes-swing",
              "piano-whole-note-swing"
            ]
          }
        ]
      }
    ]
  },
  "piano-bossa-sparse": {
    "id": "piano-bossa-sparse",
    "style": "bossa",
    "length": 8,
    "timeSignature": [
      4,
      4
    ],
    "velocity": 0.8,
    "dynamics": {
      "type": "steady",
      "amount": 0
    },
    "lanes": [
      {
        "name": "comping",
        "probability": 1,
        "clips": [
          {
            "startBar": 0,
            "lengthBars": 2,
            "pool": [
              "piano-half-notes-bossa",
              "piano-bossa-gilberto-bossa",
              "piano-one-three-bossa"
            ]
          },
          {
            "startBar": 2,
            "lengthBars": 2,
            "pool": [
              "piano-bossa-gilberto-bossa",
              "piano-half-notes-bossa",
              "piano-bossa-gilberto-bossa"
            ]
          },
          {
            "startBar": 4,
            "lengthBars": 2,
            "pool": [
              "piano-half-notes-bossa",
              "piano-bossa-gilberto-bossa",
              "piano-two-and-four-bossa"
            ]
          },
          {
            "startBar": 6,
            "lengthBars": 2,
            "pool": [
              "piano-bossa-gilberto-bossa",
              "piano-half-notes-bossa",
              "piano-bossa-sync-bossa"
            ]
          }
        ]
      }
    ]
  },
  "piano-bossa-medium": {
    "id": "piano-bossa-medium",
    "style": "bossa",
    "length": 8,
    "timeSignature": [
      4,
      4
    ],
    "velocity": 0.8,
    "dynamics": {
      "type": "steady",
      "amount": 0
    },
    "lanes": [
      {
        "name": "comping",
        "probability": 1,
        "clips": [
          {
            "startBar": 0,
            "lengthBars": 2,
            "pool": [
              "piano-bossa-gilberto-bossa",
              "piano-bossa-sync-bossa",
              "piano-bossa-full-bossa"
            ]
          },
          {
            "startBar": 2,
            "lengthBars": 2,
            "pool": [
              "piano-bossa-full-bossa",
              "piano-bossa-gilberto-bossa",
              "piano-bossa-sync-bossa"
            ]
          },
          {
            "startBar": 4,
            "lengthBars": 2,
            "pool": [
              "piano-bossa-sync-bossa",
              "piano-bossa-full-bossa",
              "piano-bossa-gilberto-bossa"
            ]
          },
          {
            "startBar": 6,
            "lengthBars": 2,
            "pool": [
              "piano-bossa-full-bossa",
              "piano-bossa-sync-bossa",
              "piano-bossa-full-bossa"
            ]
          }
        ]
      }
    ]
  },
  "piano-bossa-dense": {
    "id": "piano-bossa-dense",
    "style": "bossa",
    "length": 8,
    "timeSignature": [
      4,
      4
    ],
    "velocity": 0.8,
    "dynamics": {
      "type": "steady",
      "amount": 0
    },
    "lanes": [
      {
        "name": "comping",
        "probability": 1,
        "clips": [
          {
            "startBar": 0,
            "lengthBars": 2,
            "pool": [
              "piano-bossa-full-bossa",
              "piano-bossa-sync-bossa",
              "piano-quarter-comp-bossa"
            ]
          },
          {
            "startBar": 2,
            "lengthBars": 2,
            "pool": [
              "piano-bossa-sync-bossa",
              "piano-bossa-full-bossa",
              "piano-quarter-comp-bossa"
            ]
          },
          {
            "startBar": 4,
            "lengthBars": 2,
            "pool": [
              "piano-bossa-full-bossa",
              "piano-quarter-comp-bossa",
              "piano-bossa-sync-bossa"
            ]
          },
          {
            "startBar": 6,
            "lengthBars": 2,
            "pool": [
              "piano-bossa-sync-bossa",
              "piano-bossa-full-bossa",
              "piano-bossa-full-bossa"
            ]
          }
        ]
      }
    ]
  },
  "piano-funk-sparse": {
    "id": "piano-funk-sparse",
    "style": "funk",
    "length": 8,
    "timeSignature": [
      4,
      4
    ],
    "velocity": 0.8,
    "dynamics": {
      "type": "steady",
      "amount": 0
    },
    "lanes": [
      {
        "name": "comping",
        "probability": 1,
        "clips": [
          {
            "startBar": 0,
            "lengthBars": 2,
            "pool": [
              "piano-two-and-four-funk",
              "piano-funk-sync-funk",
              "piano-funk-tight-funk"
            ]
          },
          {
            "startBar": 2,
            "lengthBars": 2,
            "pool": [
              "piano-funk-tight-funk",
              "piano-two-and-four-funk",
              "piano-funk-sync-funk"
            ]
          },
          {
            "startBar": 4,
            "lengthBars": 2,
            "pool": [
              "piano-two-and-four-funk",
              "piano-funk-tight-funk",
              "piano-funk-sync-funk"
            ]
          },
          {
            "startBar": 6,
            "lengthBars": 2,
            "pool": [
              "piano-funk-sync-funk",
              "piano-two-and-four-funk",
              "piano-funk-tight-funk"
            ]
          }
        ]
      }
    ]
  },
  "piano-funk-medium": {
    "id": "piano-funk-medium",
    "style": "funk",
    "length": 8,
    "timeSignature": [
      4,
      4
    ],
    "velocity": 0.8,
    "dynamics": {
      "type": "steady",
      "amount": 0
    },
    "lanes": [
      {
        "name": "comping",
        "probability": 1,
        "clips": [
          {
            "startBar": 0,
            "lengthBars": 2,
            "pool": [
              "piano-funk-sync-funk",
              "piano-funk-tight-funk",
              "piano-funk-sixteenths-funk"
            ]
          },
          {
            "startBar": 2,
            "lengthBars": 2,
            "pool": [
              "piano-funk-tight-funk",
              "piano-funk-sync-funk",
              "piano-funk-sixteenths-funk"
            ]
          },
          {
            "startBar": 4,
            "lengthBars": 2,
            "pool": [
              "piano-funk-sixteenths-funk",
              "piano-funk-tight-funk",
              "piano-funk-sync-funk"
            ]
          },
          {
            "startBar": 6,
            "lengthBars": 2,
            "pool": [
              "piano-funk-sync-funk",
              "piano-funk-sixteenths-funk",
              "piano-funk-tight-funk"
            ]
          }
        ]
      }
    ]
  },
  "piano-funk-dense": {
    "id": "piano-funk-dense",
    "style": "funk",
    "length": 8,
    "timeSignature": [
      4,
      4
    ],
    "velocity": 0.8,
    "dynamics": {
      "type": "steady",
      "amount": 0
    },
    "lanes": [
      {
        "name": "comping",
        "probability": 1,
        "clips": [
          {
            "startBar": 0,
            "lengthBars": 2,
            "pool": [
              "piano-funk-sixteenths-funk",
              "piano-funk-tight-funk",
              "piano-funk-sync-funk"
            ]
          },
          {
            "startBar": 2,
            "lengthBars": 2,
            "pool": [
              "piano-funk-tight-funk",
              "piano-funk-sixteenths-funk",
              "piano-funk-sync-funk"
            ]
          },
          {
            "startBar": 4,
            "lengthBars": 2,
            "pool": [
              "piano-funk-sixteenths-funk",
              "piano-funk-sync-funk",
              "piano-funk-tight-funk"
            ]
          },
          {
            "startBar": 6,
            "lengthBars": 2,
            "pool": [
              "piano-funk-sync-funk",
              "piano-funk-sixteenths-funk",
              "piano-funk-tight-funk"
            ]
          }
        ]
      }
    ]
  },
  "piano-latin-montuno": {
    "id": "piano-latin-montuno",
    "style": "latin",
    "length": 8,
    "timeSignature": [
      4,
      4
    ],
    "velocity": 0.8,
    "dynamics": {
      "type": "steady",
      "amount": 0
    },
    "lanes": [
      {
        "name": "comping",
        "probability": 1,
        "clips": [
          {
            "startBar": 0,
            "lengthBars": 2,
            "pool": [
              "piano-montuno-latin",
              "piano-montuno-variant-latin",
              "piano-montuno-dense-latin"
            ]
          },
          {
            "startBar": 2,
            "lengthBars": 2,
            "pool": [
              "piano-montuno-variant-latin",
              "piano-montuno-latin",
              "piano-montuno-dense-latin"
            ]
          },
          {
            "startBar": 4,
            "lengthBars": 2,
            "pool": [
              "piano-montuno-latin",
              "piano-montuno-dense-latin",
              "piano-montuno-variant-latin"
            ]
          },
          {
            "startBar": 6,
            "lengthBars": 2,
            "pool": [
              "piano-montuno-latin",
              "piano-montuno-variant-latin",
              "piano-montuno-latin"
            ]
          }
        ]
      }
    ]
  },
  "piano-latin-sparse": {
    "id": "piano-latin-sparse",
    "style": "latin",
    "length": 8,
    "timeSignature": [
      4,
      4
    ],
    "velocity": 0.8,
    "dynamics": {
      "type": "steady",
      "amount": 0
    },
    "lanes": [
      {
        "name": "comping",
        "probability": 1,
        "clips": [
          {
            "startBar": 0,
            "lengthBars": 2,
            "pool": [
              "piano-half-notes-latin",
              "piano-montuno-latin",
              "piano-montuno-variant-latin"
            ]
          },
          {
            "startBar": 2,
            "lengthBars": 2,
            "pool": [
              "piano-montuno-latin",
              "piano-half-notes-latin",
              "piano-montuno-latin"
            ]
          },
          {
            "startBar": 4,
            "lengthBars": 2,
            "pool": [
              "piano-half-notes-latin",
              "piano-montuno-variant-latin",
              "piano-montuno-latin"
            ]
          },
          {
            "startBar": 6,
            "lengthBars": 2,
            "pool": [
              "piano-montuno-variant-latin",
              "piano-half-notes-latin",
              "piano-montuno-variant-latin"
            ]
          }
        ]
      }
    ]
  },
  "piano-latin-dense": {
    "id": "piano-latin-dense",
    "style": "latin",
    "length": 8,
    "timeSignature": [
      4,
      4
    ],
    "velocity": 0.8,
    "dynamics": {
      "type": "steady",
      "amount": 0
    },
    "lanes": [
      {
        "name": "comping",
        "probability": 1,
        "clips": [
          {
            "startBar": 0,
            "lengthBars": 2,
            "pool": [
              "piano-montuno-dense-latin",
              "piano-montuno-latin",
              "piano-montuno-variant-latin"
            ]
          },
          {
            "startBar": 2,
            "lengthBars": 2,
            "pool": [
              "piano-montuno-latin",
              "piano-montuno-dense-latin",
              "piano-montuno-dense-latin"
            ]
          },
          {
            "startBar": 4,
            "lengthBars": 2,
            "pool": [
              "piano-montuno-dense-latin",
              "piano-montuno-variant-latin",
              "piano-montuno-latin"
            ]
          },
          {
            "startBar": 6,
            "lengthBars": 2,
            "pool": [
              "piano-montuno-variant-latin",
              "piano-montuno-dense-latin",
              "piano-montuno-variant-latin"
            ]
          }
        ]
      }
    ]
  },
  "piano-ballad-sparse": {
    "id": "piano-ballad-sparse",
    "style": "ballad",
    "length": 8,
    "timeSignature": [
      4,
      4
    ],
    "velocity": 0.8,
    "dynamics": {
      "type": "steady",
      "amount": 0
    },
    "lanes": [
      {
        "name": "comping",
        "probability": 1,
        "clips": [
          {
            "startBar": 0,
            "lengthBars": 2,
            "pool": [
              "piano-ballad-whole-ballad",
              "piano-ballad-half-ballad",
              "piano-ballad-whole-ballad"
            ]
          },
          {
            "startBar": 2,
            "lengthBars": 2,
            "pool": [
              "piano-ballad-half-ballad",
              "piano-ballad-whole-ballad",
              "piano-ballad-half-ballad"
            ]
          },
          {
            "startBar": 4,
            "lengthBars": 2,
            "pool": [
              "piano-ballad-whole-ballad",
              "piano-ballad-half-ballad",
              "piano-ballad-whole-ballad"
            ]
          },
          {
            "startBar": 6,
            "lengthBars": 2,
            "pool": [
              "piano-ballad-half-ballad",
              "piano-ballad-whole-ballad",
              "piano-ballad-half-ballad"
            ]
          }
        ]
      }
    ]
  },
  "piano-ballad-medium": {
    "id": "piano-ballad-medium",
    "style": "ballad",
    "length": 8,
    "timeSignature": [
      4,
      4
    ],
    "velocity": 0.8,
    "dynamics": {
      "type": "steady",
      "amount": 0
    },
    "lanes": [
      {
        "name": "comping",
        "probability": 1,
        "clips": [
          {
            "startBar": 0,
            "lengthBars": 2,
            "pool": [
              "piano-ballad-half-ballad",
              "piano-ballad-push-ballad",
              "piano-ballad-half-ballad"
            ]
          },
          {
            "startBar": 2,
            "lengthBars": 2,
            "pool": [
              "piano-ballad-push-ballad",
              "piano-ballad-half-ballad",
              "piano-quarter-notes-ballad"
            ]
          },
          {
            "startBar": 4,
            "lengthBars": 2,
            "pool": [
              "piano-ballad-half-ballad",
              "piano-ballad-push-ballad",
              "piano-quarter-notes-ballad"
            ]
          },
          {
            "startBar": 6,
            "lengthBars": 2,
            "pool": [
              "piano-ballad-push-ballad",
              "piano-ballad-half-ballad",
              "piano-ballad-push-ballad"
            ]
          }
        ]
      }
    ]
  },
  "piano-ballad-intro": {
    "id": "piano-ballad-intro",
    "style": "ballad",
    "length": 8,
    "timeSignature": [
      4,
      4
    ],
    "velocity": 0.8,
    "dynamics": {
      "type": "steady",
      "amount": 0
    },
    "lanes": [
      {
        "name": "comping",
        "probability": 1,
        "clips": [
          {
            "startBar": 0,
            "lengthBars": 2,
            "pool": [
              "piano-ballad-whole-ballad",
              "piano-ballad-whole-ballad",
              "piano-ballad-half-ballad"
            ]
          },
          {
            "startBar": 2,
            "lengthBars": 2,
            "pool": [
              "piano-ballad-whole-ballad",
              "piano-ballad-half-ballad",
              "piano-ballad-whole-ballad"
            ]
          },
          {
            "startBar": 4,
            "lengthBars": 2,
            "pool": [
              "piano-ballad-half-ballad",
              "piano-ballad-half-ballad",
              "piano-ballad-whole-ballad"
            ]
          },
          {
            "startBar": 6,
            "lengthBars": 2,
            "pool": [
              "piano-ballad-half-ballad",
              "piano-ballad-push-ballad",
              "piano-ballad-half-ballad"
            ]
          }
        ]
      }
    ]
  },
  "piano-swing-extended": {
    "id": "piano-swing-extended",
    "style": "swing",
    "length": 8,
    "timeSignature": [
      4,
      4
    ],
    "velocity": 0.8,
    "dynamics": {
      "type": "steady",
      "amount": 0
    },
    "lanes": [
      {
        "name": "comping",
        "probability": 1,
        "clips": [
          {
            "startBar": 0,
            "lengthBars": 2,
            "pool": [
              "piano-basie-2-4-swing",
              "piano-half-notes-swing",
              "piano-charleston-swing"
            ]
          },
          {
            "startBar": 2,
            "lengthBars": 2,
            "pool": [
              "piano-charleston-swing",
              "piano-garland-swing",
              "piano-basie-2-4-swing"
            ]
          },
          {
            "startBar": 4,
            "lengthBars": 2,
            "pool": [
              "piano-garland-swing",
              "piano-bossa-top-swing",
              "piano-charleston-swing"
            ]
          },
          {
            "startBar": 6,
            "lengthBars": 2,
            "pool": [
              "piano-kelly-push-swing",
              "piano-garland-swing",
              "piano-offbeat-2-4-swing"
            ]
          }
        ]
      },
      {
        "name": "fill",
        "probability": 0.15,
        "clips": [
          {
            "startBar": 3,
            "lengthBars": 1,
            "pool": [
              "piano-pass-chromatic-above-swing",
              "piano-pass-diatonic-ii-v-swing"
            ]
          },
          {
            "startBar": 7,
            "lengthBars": 1,
            "pool": [
              "piano-pass-tritone-sub-swing",
              "piano-pass-dim-7-swing"
            ]
          }
        ]
      },
      {
        "name": "accent",
        "probability": 0.18,
        "clips": [
          {
            "startBar": 0,
            "lengthBars": 1,
            "pool": [
              "piano-two-and-four-swing",
              "piano-anticipation-push-swing"
            ]
          },
          {
            "startBar": 4,
            "lengthBars": 1,
            "pool": [
              "piano-one-three-swing",
              "piano-one-twoand-four-swing"
            ]
          }
        ]
      }
    ]
  },
  "piano-bossa-extended": {
    "id": "piano-bossa-extended",
    "style": "bossa",
    "length": 8,
    "timeSignature": [
      4,
      4
    ],
    "velocity": 0.8,
    "dynamics": {
      "type": "steady",
      "amount": 0
    },
    "lanes": [
      {
        "name": "comping",
        "probability": 1,
        "clips": [
          {
            "startBar": 0,
            "lengthBars": 2,
            "pool": [
              "piano-bossa-gilberto-bossa",
              "piano-half-notes-bossa",
              "piano-bossa-sync-bossa"
            ]
          },
          {
            "startBar": 2,
            "lengthBars": 2,
            "pool": [
              "piano-bossa-sync-bossa",
              "piano-bossa-gilberto-bossa",
              "piano-bossa-full-bossa"
            ]
          },
          {
            "startBar": 4,
            "lengthBars": 2,
            "pool": [
              "piano-bossa-full-bossa",
              "piano-bossa-sync-bossa",
              "piano-bossa-gilberto-bossa"
            ]
          },
          {
            "startBar": 6,
            "lengthBars": 2,
            "pool": [
              "piano-bossa-gilberto-bossa",
              "piano-bossa-full-bossa",
              "piano-half-notes-bossa"
            ]
          }
        ]
      },
      {
        "name": "fill",
        "probability": 0.15,
        "clips": [
          {
            "startBar": 3,
            "lengthBars": 1,
            "pool": [
              "piano-pass-backdoor-bossa",
              "piano-pass-chromatic-below-bossa"
            ]
          },
          {
            "startBar": 7,
            "lengthBars": 1,
            "pool": [
              "piano-pass-diatonic-ii-v-bossa",
              "piano-pass-tritone-sub-bossa"
            ]
          }
        ]
      },
      {
        "name": "accent",
        "probability": 0.18,
        "clips": [
          {
            "startBar": 0,
            "lengthBars": 1,
            "pool": [
              "piano-one-three-bossa",
              "piano-bossa-sync-bossa"
            ]
          },
          {
            "startBar": 4,
            "lengthBars": 1,
            "pool": [
              "piano-charleston-bossa",
              "piano-two-and-four-bossa"
            ]
          }
        ]
      }
    ]
  },
  "piano-funk-extended": {
    "id": "piano-funk-extended",
    "style": "funk",
    "length": 8,
    "timeSignature": [
      4,
      4
    ],
    "velocity": 0.8,
    "dynamics": {
      "type": "steady",
      "amount": 0
    },
    "lanes": [
      {
        "name": "comping",
        "probability": 1,
        "clips": [
          {
            "startBar": 0,
            "lengthBars": 2,
            "pool": [
              "piano-funk-sync-funk",
              "piano-funk-tight-funk",
              "piano-funk-sixteenths-funk"
            ]
          },
          {
            "startBar": 2,
            "lengthBars": 2,
            "pool": [
              "piano-funk-tight-funk",
              "piano-funk-sync-funk",
              "piano-two-and-four-funk"
            ]
          },
          {
            "startBar": 4,
            "lengthBars": 2,
            "pool": [
              "piano-funk-sixteenths-funk",
              "piano-funk-tight-funk",
              "piano-funk-sync-funk"
            ]
          },
          {
            "startBar": 6,
            "lengthBars": 2,
            "pool": [
              "piano-funk-sync-funk",
              "piano-funk-sixteenths-funk",
              "piano-funk-tight-funk"
            ]
          }
        ]
      },
      {
        "name": "fill",
        "probability": 0.15,
        "clips": [
          {
            "startBar": 3,
            "lengthBars": 1,
            "pool": [
              "piano-pass-secondary-dom-funk",
              "piano-pass-dim-approach-funk"
            ]
          },
          {
            "startBar": 7,
            "lengthBars": 1,
            "pool": [
              "piano-pass-dim-7-funk",
              "piano-pass-chromatic-above-funk"
            ]
          }
        ]
      },
      {
        "name": "accent",
        "probability": 0.18,
        "clips": [
          {
            "startBar": 0,
            "lengthBars": 1,
            "pool": [
              "piano-two-and-four-funk",
              "piano-funk-tight-funk"
            ]
          },
          {
            "startBar": 4,
            "lengthBars": 1,
            "pool": [
              "piano-funk-sixteenths-funk",
              "piano-two-and-four-funk"
            ]
          }
        ]
      }
    ]
  },
  "piano-latin-extended": {
    "id": "piano-latin-extended",
    "style": "latin",
    "length": 8,
    "timeSignature": [
      4,
      4
    ],
    "velocity": 0.8,
    "dynamics": {
      "type": "steady",
      "amount": 0
    },
    "lanes": [
      {
        "name": "comping",
        "probability": 1,
        "clips": [
          {
            "startBar": 0,
            "lengthBars": 2,
            "pool": [
              "piano-montuno-latin",
              "piano-montuno-variant-latin",
              "piano-half-notes-latin"
            ]
          },
          {
            "startBar": 2,
            "lengthBars": 2,
            "pool": [
              "piano-montuno-variant-latin",
              "piano-montuno-latin",
              "piano-montuno-dense-latin"
            ]
          },
          {
            "startBar": 4,
            "lengthBars": 2,
            "pool": [
              "piano-montuno-dense-latin",
              "piano-montuno-latin",
              "piano-montuno-variant-latin"
            ]
          },
          {
            "startBar": 6,
            "lengthBars": 2,
            "pool": [
              "piano-montuno-latin",
              "piano-montuno-dense-latin",
              "piano-montuno-variant-latin"
            ]
          }
        ]
      },
      {
        "name": "fill",
        "probability": 0.15,
        "clips": [
          {
            "startBar": 3,
            "lengthBars": 1,
            "pool": [
              "piano-pass-single-chromatic-latin",
              "piano-pass-chromatic-below-latin"
            ]
          },
          {
            "startBar": 7,
            "lengthBars": 1,
            "pool": [
              "piano-pass-enclosure-latin",
              "piano-pass-diatonic-ii-v-latin"
            ]
          }
        ]
      },
      {
        "name": "accent",
        "probability": 0.18,
        "clips": [
          {
            "startBar": 0,
            "lengthBars": 1,
            "pool": [
              "piano-montuno-latin",
              "piano-montuno-dense-latin"
            ]
          },
          {
            "startBar": 4,
            "lengthBars": 1,
            "pool": [
              "piano-montuno-variant-latin",
              "piano-montuno-latin"
            ]
          }
        ]
      }
    ]
  },
  "piano-ballad-extended": {
    "id": "piano-ballad-extended",
    "style": "ballad",
    "length": 8,
    "timeSignature": [
      4,
      4
    ],
    "velocity": 0.8,
    "dynamics": {
      "type": "steady",
      "amount": 0
    },
    "lanes": [
      {
        "name": "comping",
        "probability": 1,
        "clips": [
          {
            "startBar": 0,
            "lengthBars": 2,
            "pool": [
              "piano-ballad-half-ballad",
              "piano-ballad-whole-ballad",
              "piano-ballad-half-ballad"
            ]
          },
          {
            "startBar": 2,
            "lengthBars": 2,
            "pool": [
              "piano-ballad-push-ballad",
              "piano-ballad-half-ballad",
              "piano-ballad-whole-ballad"
            ]
          },
          {
            "startBar": 4,
            "lengthBars": 2,
            "pool": [
              "piano-ballad-half-ballad",
              "piano-ballad-push-ballad",
              "piano-quarter-notes-ballad"
            ]
          },
          {
            "startBar": 6,
            "lengthBars": 2,
            "pool": [
              "piano-ballad-half-ballad",
              "piano-ballad-whole-ballad",
              "piano-ballad-push-ballad"
            ]
          }
        ]
      },
      {
        "name": "fill",
        "probability": 0.15,
        "clips": [
          {
            "startBar": 3,
            "lengthBars": 1,
            "pool": [
              "piano-pass-chromatic-below-ballad",
              "piano-pass-backdoor-ballad"
            ]
          },
          {
            "startBar": 7,
            "lengthBars": 1,
            "pool": [
              "piano-pass-diatonic-ii-v-ballad",
              "piano-pass-tritone-sub-ballad"
            ]
          }
        ]
      },
      {
        "name": "accent",
        "probability": 0.18,
        "clips": [
          {
            "startBar": 0,
            "lengthBars": 1,
            "pool": [
              "piano-ballad-whole-ballad",
              "piano-ballad-half-ballad"
            ]
          },
          {
            "startBar": 4,
            "lengthBars": 1,
            "pool": [
              "piano-ballad-half-ballad",
              "piano-ballad-push-ballad"
            ]
          }
        ]
      }
    ]
  }
};
