/* AUTO-GENERATED by the Constructor "Опубликовать в код" action. Do not edit by hand.
 * When non-empty, this map fully replaces the base definitions. */
export const GENERATED_PIANO_ORGANISMS: Record<string, unknown> = {
  "piano-swing-sparse-org": {
    "id": "piano-swing-sparse-org",
    "style": "swing",
    "label": "Swing Sparse Form",
    "sectionMap": {
      "verseA": [
        "piano-swing-sparse"
      ],
      "verseB": [
        "piano-swing-sparse"
      ],
      "chorus": [
        "piano-swing-medium"
      ],
      "bridge": [
        "piano-basie-light-swing"
      ]
    },
    "defaultForm": [
      {
        "label": "Verse",
        "type": "verseA",
        "cellPool": [
          "piano-swing-sparse"
        ],
        "repeats": 1
      },
      {
        "label": "Chorus",
        "type": "chorus",
        "cellPool": [
          "piano-swing-medium"
        ],
        "repeats": 1
      },
      {
        "label": "Bridge",
        "type": "bridge",
        "cellPool": [
          "piano-basie-light-swing"
        ],
        "repeats": 1
      },
      {
        "label": "Chorus",
        "type": "chorus",
        "cellPool": [
          "piano-swing-medium"
        ],
        "repeats": 1
      }
    ]
  },
  "piano-swing-medium-org": {
    "id": "piano-swing-medium-org",
    "style": "swing",
    "label": "Swing Medium Form",
    "sectionMap": {
      "verseA": [
        "piano-swing-medium"
      ],
      "verseB": [
        "piano-swing-medium"
      ],
      "chorus": [
        "piano-swing-dense"
      ],
      "bridge": [
        "piano-swing-sparse"
      ]
    },
    "defaultForm": [
      {
        "label": "Verse",
        "type": "verseA",
        "cellPool": [
          "piano-swing-medium"
        ],
        "repeats": 1
      },
      {
        "label": "Chorus",
        "type": "chorus",
        "cellPool": [
          "piano-swing-dense"
        ],
        "repeats": 1
      },
      {
        "label": "Bridge",
        "type": "bridge",
        "cellPool": [
          "piano-swing-sparse"
        ],
        "repeats": 1
      },
      {
        "label": "Chorus",
        "type": "chorus",
        "cellPool": [
          "piano-swing-dense"
        ],
        "repeats": 1
      }
    ]
  },
  "piano-beginner-form": {
    "id": "piano-beginner-form",
    "style": "swing",
    "label": "Beginner Form",
    "sectionMap": {
      "verseA": [
        "piano-beginner-safe-swing"
      ],
      "verseB": [
        "piano-beginner-safe-swing"
      ],
      "chorus": [
        "piano-beginner-safe-swing"
      ],
      "bridge": [
        "piano-swing-sparse"
      ]
    },
    "defaultForm": [
      {
        "label": "Verse",
        "type": "verseA",
        "cellPool": [
          "piano-beginner-safe-swing"
        ],
        "repeats": 1
      },
      {
        "label": "Chorus",
        "type": "chorus",
        "cellPool": [
          "piano-beginner-safe-swing"
        ],
        "repeats": 1
      },
      {
        "label": "Bridge",
        "type": "bridge",
        "cellPool": [
          "piano-swing-sparse"
        ],
        "repeats": 1
      },
      {
        "label": "Chorus",
        "type": "chorus",
        "cellPool": [
          "piano-beginner-safe-swing"
        ],
        "repeats": 1
      }
    ]
  },
  "piano-bossa-sparse-form": {
    "id": "piano-bossa-sparse-form",
    "style": "bossa",
    "label": "Bossa Sparse Form",
    "sectionMap": {
      "verseA": [
        "piano-bossa-sparse"
      ],
      "verseB": [
        "piano-bossa-sparse"
      ],
      "chorus": [
        "piano-bossa-medium"
      ],
      "bridge": [
        "piano-bossa-sparse"
      ]
    },
    "defaultForm": [
      {
        "label": "Verse",
        "type": "verseA",
        "cellPool": [
          "piano-bossa-sparse"
        ],
        "repeats": 1
      },
      {
        "label": "Chorus",
        "type": "chorus",
        "cellPool": [
          "piano-bossa-medium"
        ],
        "repeats": 1
      },
      {
        "label": "Bridge",
        "type": "bridge",
        "cellPool": [
          "piano-bossa-sparse"
        ],
        "repeats": 1
      },
      {
        "label": "Chorus",
        "type": "chorus",
        "cellPool": [
          "piano-bossa-medium"
        ],
        "repeats": 1
      }
    ]
  },
  "piano-bossa-dense-form": {
    "id": "piano-bossa-dense-form",
    "style": "bossa",
    "label": "Bossa Dense Form",
    "sectionMap": {
      "verseA": [
        "piano-bossa-medium"
      ],
      "verseB": [
        "piano-bossa-medium"
      ],
      "chorus": [
        "piano-bossa-dense"
      ],
      "bridge": [
        "piano-bossa-sparse"
      ]
    },
    "defaultForm": [
      {
        "label": "Verse",
        "type": "verseA",
        "cellPool": [
          "piano-bossa-medium"
        ],
        "repeats": 1
      },
      {
        "label": "Chorus",
        "type": "chorus",
        "cellPool": [
          "piano-bossa-dense"
        ],
        "repeats": 1
      },
      {
        "label": "Bridge",
        "type": "bridge",
        "cellPool": [
          "piano-bossa-sparse"
        ],
        "repeats": 1
      },
      {
        "label": "Chorus",
        "type": "chorus",
        "cellPool": [
          "piano-bossa-dense"
        ],
        "repeats": 1
      }
    ]
  },
  "piano-funk-sparse-form": {
    "id": "piano-funk-sparse-form",
    "style": "funk",
    "label": "Funk Sparse Form",
    "sectionMap": {
      "verseA": [
        "piano-funk-sparse"
      ],
      "verseB": [
        "piano-funk-sparse"
      ],
      "chorus": [
        "piano-funk-medium"
      ],
      "bridge": [
        "piano-funk-sparse"
      ]
    },
    "defaultForm": [
      {
        "label": "Verse",
        "type": "verseA",
        "cellPool": [
          "piano-funk-sparse"
        ],
        "repeats": 1
      },
      {
        "label": "Chorus",
        "type": "chorus",
        "cellPool": [
          "piano-funk-medium"
        ],
        "repeats": 1
      },
      {
        "label": "Bridge",
        "type": "bridge",
        "cellPool": [
          "piano-funk-sparse"
        ],
        "repeats": 1
      },
      {
        "label": "Chorus",
        "type": "chorus",
        "cellPool": [
          "piano-funk-medium"
        ],
        "repeats": 1
      }
    ]
  },
  "piano-funk-dense-form": {
    "id": "piano-funk-dense-form",
    "style": "funk",
    "label": "Funk Dense Form",
    "sectionMap": {
      "verseA": [
        "piano-funk-medium"
      ],
      "verseB": [
        "piano-funk-medium"
      ],
      "chorus": [
        "piano-funk-dense"
      ],
      "bridge": [
        "piano-funk-sparse"
      ]
    },
    "defaultForm": [
      {
        "label": "Verse",
        "type": "verseA",
        "cellPool": [
          "piano-funk-medium"
        ],
        "repeats": 1
      },
      {
        "label": "Chorus",
        "type": "chorus",
        "cellPool": [
          "piano-funk-dense"
        ],
        "repeats": 1
      },
      {
        "label": "Bridge",
        "type": "bridge",
        "cellPool": [
          "piano-funk-sparse"
        ],
        "repeats": 1
      },
      {
        "label": "Chorus",
        "type": "chorus",
        "cellPool": [
          "piano-funk-dense"
        ],
        "repeats": 1
      }
    ]
  },
  "piano-latin-montuno-form": {
    "id": "piano-latin-montuno-form",
    "style": "latin",
    "label": "Latin Montuno Form",
    "sectionMap": {
      "verseA": [
        "piano-latin-sparse"
      ],
      "verseB": [
        "piano-latin-sparse"
      ],
      "chorus": [
        "piano-latin-montuno"
      ],
      "bridge": [
        "piano-latin-sparse"
      ]
    },
    "defaultForm": [
      {
        "label": "Verse",
        "type": "verseA",
        "cellPool": [
          "piano-latin-sparse"
        ],
        "repeats": 1
      },
      {
        "label": "Chorus",
        "type": "chorus",
        "cellPool": [
          "piano-latin-montuno"
        ],
        "repeats": 1
      },
      {
        "label": "Bridge",
        "type": "bridge",
        "cellPool": [
          "piano-latin-sparse"
        ],
        "repeats": 1
      },
      {
        "label": "Chorus",
        "type": "chorus",
        "cellPool": [
          "piano-latin-montuno"
        ],
        "repeats": 1
      }
    ]
  },
  "piano-latin-dense-form": {
    "id": "piano-latin-dense-form",
    "style": "latin",
    "label": "Latin Dense Form",
    "sectionMap": {
      "verseA": [
        "piano-latin-montuno"
      ],
      "verseB": [
        "piano-latin-montuno"
      ],
      "chorus": [
        "piano-latin-dense"
      ],
      "bridge": [
        "piano-latin-sparse"
      ]
    },
    "defaultForm": [
      {
        "label": "Verse",
        "type": "verseA",
        "cellPool": [
          "piano-latin-montuno"
        ],
        "repeats": 1
      },
      {
        "label": "Chorus",
        "type": "chorus",
        "cellPool": [
          "piano-latin-dense"
        ],
        "repeats": 1
      },
      {
        "label": "Bridge",
        "type": "bridge",
        "cellPool": [
          "piano-latin-sparse"
        ],
        "repeats": 1
      },
      {
        "label": "Chorus",
        "type": "chorus",
        "cellPool": [
          "piano-latin-dense"
        ],
        "repeats": 1
      }
    ]
  },
  "piano-ballad-sparse-form": {
    "id": "piano-ballad-sparse-form",
    "style": "ballad",
    "label": "Ballad Sparse Form",
    "sectionMap": {
      "verseA": [
        "piano-ballad-sparse"
      ],
      "verseB": [
        "piano-ballad-sparse"
      ],
      "chorus": [
        "piano-ballad-medium"
      ],
      "bridge": [
        "piano-ballad-sparse"
      ]
    },
    "defaultForm": [
      {
        "label": "Verse",
        "type": "verseA",
        "cellPool": [
          "piano-ballad-sparse"
        ],
        "repeats": 1
      },
      {
        "label": "Chorus",
        "type": "chorus",
        "cellPool": [
          "piano-ballad-medium"
        ],
        "repeats": 1
      },
      {
        "label": "Bridge",
        "type": "bridge",
        "cellPool": [
          "piano-ballad-sparse"
        ],
        "repeats": 1
      },
      {
        "label": "Chorus",
        "type": "chorus",
        "cellPool": [
          "piano-ballad-medium"
        ],
        "repeats": 1
      }
    ]
  },
  "piano-ballad-intro-form": {
    "id": "piano-ballad-intro-form",
    "style": "ballad",
    "label": "Ballad Intro Form",
    "sectionMap": {
      "verseA": [
        "piano-ballad-intro"
      ],
      "verseB": [
        "piano-ballad-intro"
      ],
      "chorus": [
        "piano-ballad-medium"
      ],
      "bridge": [
        "piano-ballad-sparse"
      ]
    },
    "defaultForm": [
      {
        "label": "Verse",
        "type": "verseA",
        "cellPool": [
          "piano-ballad-intro"
        ],
        "repeats": 1
      },
      {
        "label": "Chorus",
        "type": "chorus",
        "cellPool": [
          "piano-ballad-medium"
        ],
        "repeats": 1
      },
      {
        "label": "Bridge",
        "type": "bridge",
        "cellPool": [
          "piano-ballad-sparse"
        ],
        "repeats": 1
      },
      {
        "label": "Chorus",
        "type": "chorus",
        "cellPool": [
          "piano-ballad-medium"
        ],
        "repeats": 1
      }
    ]
  },
  "piano-swing-extended-form": {
    "id": "piano-swing-extended-form",
    "style": "swing",
    "label": "Swing Extended Form",
    "sectionMap": {
      "verseA": [
        "piano-swing-extended"
      ],
      "verseB": [
        "piano-swing-extended"
      ],
      "chorus": [
        "piano-swing-dense"
      ],
      "bridge": [
        "piano-swing-extended"
      ]
    },
    "defaultForm": [
      {
        "label": "Verse",
        "type": "verseA",
        "cellPool": [
          "piano-swing-extended"
        ],
        "repeats": 1
      },
      {
        "label": "Chorus",
        "type": "chorus",
        "cellPool": [
          "piano-swing-dense"
        ],
        "repeats": 1
      },
      {
        "label": "Bridge",
        "type": "bridge",
        "cellPool": [
          "piano-swing-extended"
        ],
        "repeats": 1
      },
      {
        "label": "Chorus",
        "type": "chorus",
        "cellPool": [
          "piano-swing-dense"
        ],
        "repeats": 1
      }
    ]
  },
  "piano-bossa-extended-form": {
    "id": "piano-bossa-extended-form",
    "style": "bossa",
    "label": "Bossa Extended Form",
    "sectionMap": {
      "verseA": [
        "piano-bossa-sparse"
      ],
      "verseB": [
        "piano-bossa-sparse"
      ],
      "chorus": [
        "piano-bossa-extended"
      ],
      "bridge": [
        "piano-bossa-sparse"
      ]
    },
    "defaultForm": [
      {
        "label": "Verse",
        "type": "verseA",
        "cellPool": [
          "piano-bossa-sparse"
        ],
        "repeats": 1
      },
      {
        "label": "Chorus",
        "type": "chorus",
        "cellPool": [
          "piano-bossa-extended"
        ],
        "repeats": 1
      },
      {
        "label": "Bridge",
        "type": "bridge",
        "cellPool": [
          "piano-bossa-sparse"
        ],
        "repeats": 1
      },
      {
        "label": "Chorus",
        "type": "chorus",
        "cellPool": [
          "piano-bossa-extended"
        ],
        "repeats": 1
      }
    ]
  },
  "piano-funk-extended-form": {
    "id": "piano-funk-extended-form",
    "style": "funk",
    "label": "Funk Extended Form",
    "sectionMap": {
      "verseA": [
        "piano-funk-sparse"
      ],
      "verseB": [
        "piano-funk-sparse"
      ],
      "chorus": [
        "piano-funk-extended"
      ],
      "bridge": [
        "piano-funk-sparse"
      ]
    },
    "defaultForm": [
      {
        "label": "Verse",
        "type": "verseA",
        "cellPool": [
          "piano-funk-sparse"
        ],
        "repeats": 1
      },
      {
        "label": "Chorus",
        "type": "chorus",
        "cellPool": [
          "piano-funk-extended"
        ],
        "repeats": 1
      },
      {
        "label": "Bridge",
        "type": "bridge",
        "cellPool": [
          "piano-funk-sparse"
        ],
        "repeats": 1
      },
      {
        "label": "Chorus",
        "type": "chorus",
        "cellPool": [
          "piano-funk-extended"
        ],
        "repeats": 1
      }
    ]
  },
  "piano-latin-extended-form": {
    "id": "piano-latin-extended-form",
    "style": "latin",
    "label": "Latin Extended Form",
    "sectionMap": {
      "verseA": [
        "piano-latin-sparse"
      ],
      "verseB": [
        "piano-latin-sparse"
      ],
      "chorus": [
        "piano-latin-extended"
      ],
      "bridge": [
        "piano-latin-sparse"
      ]
    },
    "defaultForm": [
      {
        "label": "Verse",
        "type": "verseA",
        "cellPool": [
          "piano-latin-sparse"
        ],
        "repeats": 1
      },
      {
        "label": "Chorus",
        "type": "chorus",
        "cellPool": [
          "piano-latin-extended"
        ],
        "repeats": 1
      },
      {
        "label": "Bridge",
        "type": "bridge",
        "cellPool": [
          "piano-latin-sparse"
        ],
        "repeats": 1
      },
      {
        "label": "Chorus",
        "type": "chorus",
        "cellPool": [
          "piano-latin-extended"
        ],
        "repeats": 1
      }
    ]
  },
  "piano-ballad-extended-form": {
    "id": "piano-ballad-extended-form",
    "style": "ballad",
    "label": "Ballad Extended Form",
    "sectionMap": {
      "verseA": [
        "piano-ballad-extended"
      ],
      "verseB": [
        "piano-ballad-extended"
      ],
      "chorus": [
        "piano-ballad-medium"
      ],
      "bridge": [
        "piano-ballad-sparse"
      ]
    },
    "defaultForm": [
      {
        "label": "Verse",
        "type": "verseA",
        "cellPool": [
          "piano-ballad-extended"
        ],
        "repeats": 1
      },
      {
        "label": "Chorus",
        "type": "chorus",
        "cellPool": [
          "piano-ballad-medium"
        ],
        "repeats": 1
      },
      {
        "label": "Bridge",
        "type": "bridge",
        "cellPool": [
          "piano-ballad-sparse"
        ],
        "repeats": 1
      },
      {
        "label": "Chorus",
        "type": "chorus",
        "cellPool": [
          "piano-ballad-medium"
        ],
        "repeats": 1
      }
    ]
  }
};
