import type { InstrumentManifest, SampleManifest } from '@jazz/music-core';
import { DrumInstrument, sampleBaseUrl } from '@jazz/music-core';
import { FUNK_DRUM_KIT_SAMPLE_FILES } from './sampleRegistry.js';

const FUNK_DRUM_KIT_SAMPLE_MANIFEST: SampleManifest = {
  baseUrl: sampleBaseUrl('drums', 'funk-drum-kit', 'aac'),
  fallbackBaseUrl: sampleBaseUrl('drums', 'funk-drum-kit', 'mp3'),
  velocityOneshots: FUNK_DRUM_KIT_SAMPLE_FILES,
  velocityLayers: ['vl1', 'vl2', 'vl3', 'vl4', 'vl5'],
  rrCount: 4,
};

export const funkDrumKitManifest: InstrumentManifest = {
  id: 'funk-drum-kit',
  name: 'Funk Drum Kit',
  family: 'drums',
  settingsPrefix: 'drums',
  createInstrument: () => new DrumInstrument(),
  sampleManifest: FUNK_DRUM_KIT_SAMPLE_MANIFEST,
  defaultSettings: {
    enabled: true,
    volume: 0.75,
    // Core sounds
    bassDrumEnabled: true,
    bassDrumVolume: 0.75,
    snareEnabled: true,
    snareVolume: 0.8,
    hihatEnabled: true,
    hihatVolume: 0.7,
    hihatOpenness: 0,
    rideEnabled: true,
    rideVolume: 0.7,
    crashEnabled: true,
    crashVolume: 0.8,
    rimEnabled: false,
    rimVolume: 0.6,
    tomEnabled: true,
    tomVolume: 0.7,
    // Funk-specific articulations
    snareBuzzEnabled: true,
    snareBuzzVolume: 0.4,
    snareFlamEnabled: true,
    snareFlamVolume: 0.5,
    snareRimshotEnabled: true,
    snareRimshotVolume: 0.75,
    snareCrossstickEnabled: true,
    snareCrossstickVolume: 0.6,
    snareMutedEnabled: true,
    snareMutedVolume: 0.45,
    rideBellEnabled: true,
    rideBellVolume: 0.7,
    crashSizzleEnabled: true,
    crashSizzleVolume: 0.7,
    useArticulations: true,
    // Not in Funk Kit
    snareEdgeEnabled: false,
    snareEdgeVolume: 0.6,
    snareDigEnabled: false,
    snareDigVolume: 0.5,
    stirEnabled: false,
    stirVolume: 0.6,
    splashEnabled: false,
    splashVolume: 0.7,
  },
  perStyleDefaults: {
    swing: {
      pattern: 'swing',
      snareBuzzEnabled: false,
      snareFlamEnabled: false,
      snareRimshotEnabled: false,
      rideBellEnabled: false,
      crashSizzleEnabled: false,
    },
    bossa: {
      pattern: 'bossa',
      snareEnabled: false,
      snareCrossstickEnabled: true,
      rimEnabled: true,
      snareBuzzEnabled: false,
      snareFlamEnabled: false,
      snareRimshotEnabled: false,
      tomEnabled: false,
    },
    funk: {
      pattern: 'funk',
      snareBuzzEnabled: true,
      snareFlamEnabled: true,
      snareRimshotEnabled: true,
      rideBellEnabled: true,
      crashSizzleEnabled: true,
      tomEnabled: true,
    },
    latin: {
      pattern: 'funk',
      snareBuzzEnabled: true,
      snareRimshotEnabled: true,
      tomEnabled: true,
    },
    ballad: {
      pattern: 'swing',
      volume: 0.6,
      snareBuzzEnabled: false,
      snareFlamEnabled: false,
      snareRimshotEnabled: false,
      rideBellEnabled: false,
      crashSizzleEnabled: false,
    },
  },
};
