import type { FastifyInstance } from 'fastify';
import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { requireAuth } from '../plugins/auth.plugin.js';
import { requirePermission } from '../plugins/rbac.plugin.js';
import { DrumSourcePayloadSchema } from '@jazz/shared';

/**
 * Dev-only routes. Registered ТОЛЬКО при config.authDevMode === true.
 * Позволяют Конструктору барабанов сохранять отредактированные клетки/молекулы
 * прямо в исходники music-core (сгенерированные файлы, замещающие базовые).
 */
export async function devRoutes(fastify: FastifyInstance): Promise<void> {
  const audioDir = fileURLToPath(
    new URL('../../../../packages/music-core/src/audio/', import.meta.url),
  );

  const banner =
    '/* AUTO-GENERATED by the Drum Constructor "Сохранить" action. Do not edit by hand.\n' +
    ' * When non-empty, this map fully replaces the base definitions. */\n';

  fastify.post(
    '/dev/drum-source',
    { preHandler: [requireAuth, requirePermission('content:write')] },
    async (request, reply) => {
      // Validate the payload against the Drum Constructor contract before
      // anything is written to source files. Zod gives structured, field-level
      // error messages so the admin UI can show exactly what's wrong instead
      // of the previous "Ожидались объекты cells и molecules" catch-all.
      const parsed = DrumSourcePayloadSchema.safeParse(request.body);
      if (!parsed.success) {
        return reply.status(400).send({
          error: {
            code: 'VALIDATION_ERROR',
            message: 'Невалидный payload Конструктора барабанов',
            issues: parsed.error.issues,
          },
        });
      }

      const { cells, molecules, organisms } = parsed.data;

      const cellsFile =
        banner +
        `export const GENERATED_DRUM_CELLS: Record<string, unknown> = ${JSON.stringify(cells, null, 2)};\n`;
      const molsFile =
        banner +
        `export const GENERATED_DRUM_MOLECULES: Record<string, unknown> = ${JSON.stringify(molecules, null, 2)};\n`;

      await writeFile(`${audioDir}drumCellsGenerated.ts`, cellsFile, 'utf8');
      await writeFile(`${audioDir}drumMoleculesGenerated.ts`, molsFile, 'utf8');

      // organisms is optional — when present, overwrite the generated file;
      // when omitted, leave the existing one untouched (so a cells-only edit
      // doesn't wipe the organisms the admin saved previously).
      if (organisms) {
        const orgsFile =
          banner +
          `export const GENERATED_DRUM_ORGANISMS: Record<string, unknown> = ${JSON.stringify(organisms, null, 2)};\n`;
        await writeFile(`${audioDir}drumOrganismsGenerated.ts`, orgsFile, 'utf8');
      }

      return {
        ok: true,
        cells: Object.keys(cells).length,
        molecules: Object.keys(molecules).length,
        organisms: organisms ? Object.keys(organisms).length : 0,
      };
    },
  );
}
