/**
 * Jazz Drum Kit sample registry — 4 velocity layers.
 *
 * Naming: <articulation>_vl<layer>_rr<index>.m4a
 * Layers: vl5 (p), vl10 (mf), vl15 (f), vl20 (ff)
 *
 * Generated by: scripts/encode-drums-jazz.sh
 */
import type { DrumSound } from '@jazz/music-core';
import { buildVelocityRR } from '@jazz/music-core';

/** Ordered velocity layers from quietest to loudest. */
export const JAZZ_VELOCITY_LAYERS = ['vl5', 'vl10', 'vl15', 'vl20'] as const;

/** Jazz Kit oneshots: sound → velocity layer → [rr filenames]. */
export const JAZZ_DRUM_KIT_SAMPLE_FILES: Record<string, Record<string, string[]>> = {
  kick: buildVelocityRR('kick', JAZZ_VELOCITY_LAYERS),

  // Snare articulations (top mic)
  snare_center: buildVelocityRR('center', JAZZ_VELOCITY_LAYERS),
  snare_edge: buildVelocityRR('edge', JAZZ_VELOCITY_LAYERS),
  snare_dig: buildVelocityRR('dig', JAZZ_VELOCITY_LAYERS),

  // Hi-hat articulations
  hihat_closed: buildVelocityRR('closed', JAZZ_VELOCITY_LAYERS),
  hihat_tight: buildVelocityRR('tight', JAZZ_VELOCITY_LAYERS),
  hihat_open: buildVelocityRR('open', JAZZ_VELOCITY_LAYERS),
  hihat_foot: buildVelocityRR('foot', JAZZ_VELOCITY_LAYERS),
  hihat_stir: { single: ['stir_rr1.m4a', 'stir_rr2.m4a', 'stir_rr3.m4a', 'stir_rr4.m4a'] },

  // Ride articulations
  ride_bow: buildVelocityRR('bow', JAZZ_VELOCITY_LAYERS),
  ride_bell: buildVelocityRR('bell', JAZZ_VELOCITY_LAYERS),

  // Cymbals
  crash: buildVelocityRR('crash', JAZZ_VELOCITY_LAYERS),
  splash: buildVelocityRR('splash', JAZZ_VELOCITY_LAYERS),

  // Toms
  tom_mhi: buildVelocityRR('mhi', JAZZ_VELOCITY_LAYERS),
  tom_mlow: buildVelocityRR('mlow', JAZZ_VELOCITY_LAYERS),
};

/**
 * Maps legacy DrumSound names to their articulation equivalents for Jazz Kit.
 * Used by the articulation resolver to route old sound names → new sample keys.
 */
export const JAZZ_ARTICULATION_MAP: Partial<Record<DrumSound, DrumSound>> = {
  bassDrum: 'kick',
  snare: 'snare_center',
  hihat: 'hihat_closed',
  hihatHalf: 'hihat_closed',
  hihatOpen: 'hihat_open',
  ride: 'ride_bow',
  crash: 'crash',
  rim: 'snare_edge',
  highTom: 'tom_mhi',
  lowTom: 'tom_mlow',
};
