import type { InstrumentManifest, SampleManifest } from '@jazz/music-core';
import { PercussionInstrument, sampleBaseUrl } from '@jazz/music-core';
import { PERCUSSION_SAMPLE_FILES } from './sampleRegistry.js';

const PERCUSSION_SAMPLE_MANIFEST: SampleManifest = {
  baseUrl: sampleBaseUrl('percussion', 'percussion', 'aac'),
  fallbackBaseUrl: sampleBaseUrl('percussion', 'percussion', 'mp3'),
  oneshots: PERCUSSION_SAMPLE_FILES,
  rrCount: 4,
};

export const percussionManifest: InstrumentManifest = {
  id: 'percussion',
  name: 'Percussion',
  family: 'percussion',
  settingsPrefix: 'percussion',
  sounds: [
    'congaHigh',
    'congaLow',
    'bongoLow',
    'tumba',
    'timbales',
    'cowbell',
    'clave',
    'shaker',
    'guiro',
    'cabasa',
    'triangle',
    'tambourine',
    'vibraslap',
    'belltree',
    'whistle',
    'sleighBells',
  ],
  createInstrument: () => new PercussionInstrument(),
  sampleManifest: PERCUSSION_SAMPLE_MANIFEST,
  defaultSettings: {
    enabled: false,
    volume: 0.7,
    pattern: 'cascara-clave',
    organismId: null,
    congaHighEnabled: true,
    congaHighVolume: 0.7,
    congaLowEnabled: true,
    congaLowVolume: 0.75,
    timbalesEnabled: true,
    timbalesVolume: 0.65,
    cowbellEnabled: true,
    cowbellVolume: 0.6,
    claveEnabled: true,
    claveVolume: 0.7,
    shakerEnabled: true,
    shakerVolume: 0.55,
    guiroEnabled: true,
    guiroVolume: 0.5,
    triangleEnabled: true,
    triangleVolume: 0.5,
    bongoLowEnabled: false,
    bongoLowVolume: 0.65,
    tumbaEnabled: false,
    tumbaVolume: 0.7,
    cabasaEnabled: false,
    cabasaVolume: 0.55,
    tambourineEnabled: false,
    tambourineVolume: 0.5,
    vibraslapEnabled: false,
    vibraslapVolume: 0.55,
    belltreeEnabled: false,
    belltreeVolume: 0.45,
    whistleEnabled: false,
    whistleVolume: 0.5,
    sleighBellsEnabled: false,
    sleighBellsVolume: 0.4,
    humanizeIntensity: 'low',
  },
  perStyleDefaults: {
    swing: { enabled: false },
    bossa: { organismId: 'bossa-default', enabled: true },
    funk: { organismId: 'funk-default', enabled: true },
    latin: { organismId: 'latin-default', enabled: true },
    ballad: { enabled: false },
  },
};
